- Joystick/Joystick.cs
Previously joystick file did try to load from local folder, which is not where setup files are stored, that's why joystick setup wasn't loaded or saved.
> Fix for joystick setup file load issue #1388

- ExtLibs/SharpAdbClient/AdbSocket.cs
- Utilities/BoardDetect.cs
- Utilities/Firmware.cs
- temp.cs
This changes the firmware installation in Bebop2. It will now install the binary in /data/ftp/internal_000/APM (instead of /usr/bin) - not only this allows bigger binaries but you can change the binary with FTP, no need for adb and remount. Also the init scripts have been changed to:
- have a startup_ardupilot.sh script in the APM folder that starts the fan, logs the start of ArduPilot, and puts the running of ArduPilot in a cycle so that we can reboot with MAVLink
- test if the startup_ardupilot.sh script as well as the arducopter binary are present in the APM folder
- run the startup_ardupilot.sh script if last check is true
- run Dragon if any of them isn't (this guarantees you always have an autopilot running)
The backup of the init (rcS_mode_default) script was also changed to only …
> Improve Parrot firmware install process

- GCSViews/FlightData.cs
This just checks if "Graph This" form is already open, and if it is open it brings that form to front.
> flightdata: bring Graph This form to front insted of creating new form every time

- mavcmd.xml
This label is old and needs to be removed. It is not parsed, always treated as 1 internal to ArduPilot.
See https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mission/AP_Mission.cpp#L550 as an example where P2 is ignored in LOITER_TURNS and LOITER_TIME and it's P1 in LOITER_TO_ALT.
> Remove NAV_LOITER 'Heading req' param text, its always enforced

- Log/MavlinkLog.cs
This bug is caused when mavlink message name has _t in it. For example mavlink_pid_tuning_t. Old code would remove both _t which would result in name PIDUNING
Before fix:
After fix:
> TelemetryLogGraph: Fix some messages not being graphed

- Utilities/Tools.cs
null pointer  `o` was thrown to `ToUnsigned` method
> null check

- LogAnalyzer/py2exe/tests/TestVCC.py
The Navio2 uses `Volt`: instead of `Vcc`
> removed KeyError: 'POWR'

- SerialInjectGPS.cs
https://community.emlid.com/t/rtk-inject-with-mission-planner-error/6666
MP seems do not get well with emlid reach Beidou RTCM message (message 1127).  MP will build a type1127 instance with empty obs list. This cause exception when obs[0].sys called.
> work around for emlid reach Beidou RTCM message parsing

- SerialInjectGPS.cs
MAVLinkInterface::InjectGpsData take length as ushort and it can handle data up to 720 bytes, but SerialInjectGPS::sendData send length as byte when call InjectGpsData.
> SerialInjectGPS: match sendData length variable type to InjectGpsData

- Grid/GridUI.cs
Hi ,
I'm opening the pull request of fixing missing flight strip when doing segmentation in GridUI.
This is the one that we've talked about during the Ardupilot Unconference last week. @meee1 
When planning a survey mission with 4 strips and 2 segments in 1.3.50, the latter segment missed a flight strip.
After the fixing.
I've tested in some other conditions, and as far as I'm concerned, this change will not lead to other bugs.
Shuhang Zhang
> Fix missing flight strip bug when doing segmentation in GridUI

- ExtLibs/Utilities/Capture.cs
Each time the FlightData tab is selected, it registers to the event again and again.
> Prevent multiple register to video captue event

- README.md
Changing to VS 2017 and indicating need for .NET standard 2.0 so newcomers to the project have some clues as to why library references are broken.
> Updating sw and build requirements (VS)

- ExtLibs/Utilities/DisplayView.cs
- GCSViews/ConfigurationView/ConfigFlightModes.cs
- GCSViews/ConfigurationView/ConfigHWCompass.cs
- GCSViews/FlightData.Designer.cs
- GCSViews/FlightPlanner.cs
- GCSViews/InitialSetup.cs
- GCSViews/SoftwareConfig.cs
- MainV2.cs
These changes expand on the existing display view feature for creating custom layouts and allow developers to have finer control over what configuration options are available to the end user.
> Expanded on the configuration options of the "display view" feature

- GCSViews/FlightPlanner.de-DE.resx
I had to change the name "Höhendatenschreiber" ("height data writer") to "Zeige WP- zu Terrainhöhen". Which can be translated to "Show W(ay)P(oint) to terrain heights".
Every thing else is just a byproduct...
> Revised german translation

- ExtLibs/Utilities/DisplayView.cs
- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.resx
- GCSViews/ConfigurationView/ConfigRawParams.Designer.cs
- GCSViews/ConfigurationView/ConfigRawParams.cs
- GCSViews/ConfigurationView/ConfigRawParams.resx
- GCSViews/ConfigurationView/ConfigRawParamsTree.Designer.cs
- GCSViews/ConfigurationView/ConfigRawParamsTree.cs
- GCSViews/ConfigurationView/ConfigRawParamsTree.resx
- Mavlink/MAVLinkInterface.cs
also fixed ctrl+Y command so that it sends a write params command
rather than a read params command
This change is to support components other than flight controllers running ardupilot which require a PREFLIGHT_STORAGE command to save params to non-volatile memory as per the mavlink standard.
> Added ability to commit params to flash in param list/tree

- ExtLibs/Utilities/Matrix3.cs
- ExtLibs/Utilities/Vector3.cs
Resolves exceptions being thrown when DCM normalisation method is
called and prevents misinterpretation of * operator when multiplying
a vector by the result of a dot product
> Vector3: changed dot product overload to output a scalar #1712

- GCSViews/FlightData.Designer.cs
- GCSViews/FlightData.cs
- GCSViews/FlightData.resx
- MainV2.cs
Adds a tab with a series of sliders to the Flight Data page
for testing/controlling gimbals that only operate via mavlink
messages using the mount control interface on ardupilot flight
controllers. This tab will appear when mission planner is
connected to a flight controller and a mavlink gimbal hearbeat is
detected on the same system ID.
> simple interface tab for MavLink Gimbals

- GCSViews/ConfigurationView/ConfigPlanner.cs
unchecking the box will now close the temp form and closing the
temp form spawned by the planner view will uncheck the checkbox
> Fixed testing screen checkbox behaviour in config planner view

- GCSViews/FlightPlanner.cs
I change the error message "Lng" to the item name "Long".
That is because the error message was incorrect in the input of the item.
I think this error message is for users.
> FlightPlanner: Change the error message to item name

- GCSViews/FlightData.cs
- GCSViews/FlightPlanner.Designer.cs
- GCSViews/FlightPlanner.cs
When row is deleted from grid in flight planner redraw waypoints. Allow saving of map / hud swap on flightdata view. Fixed bug in saving hud width... changed to save splitter width.
> Couple of ui tweaks

- CurrentState.cs
Added a minutes.seconds interpretation of TimeInAir to currentstate. 
I think It is easier to read the time in air if it displayed in minutes.seconds format. Added a new variable to the  currentstate seemed the easiest way to do it.
Ps. Also this is my first pull request for the Mission Planner, others will follow.
> Added a minute.second interpretation of TimeInAir to currentstate 

- Log/LogBrowse.cs
Showing all the possible messages in the filter select box isn't useful because many times logs only contain a small subset of messages.
This also sorts the options to be easier to find them.
> LogBrowse: filter options only show seen messages

- MainV2.cs
Custom HUD items are loosing data source on disconnect, and connect does not restore it.  Added it to the last stage of connect. Now custom HUD items are refreshed after a disconnect-connect.
> Reconnect HUD custom items to the main state on connect

- GCSViews/FlightData.cs
CreateOverlay is used with both views, but FlightData passes home location in wps[0] and  it is displayed as WP1 so WP numbering are off on FlightData view.
Also added workaround to display home position only when all WP-s are deleted.
> Fix mission discrepancy between FlighData and FlightPlanner mission points numbering.

- ExtLibs/Controls/HUD.cs
I'm working on a "night mode" plugin, which enables quick switch between different color schemas for night or day usage. To support this, colors used for hud sky and ground are needed to be exposed as public properties. This change does this, keeping the current values as default setting.
> Exposing sky and ground color values to support upcoming "Night MODE" plugin

- ExtLibs/Maps/Japan.cs
- ExtLibs/Maps/Japan_1974.cs
- ExtLibs/Maps/Japan_1979.cs
- ExtLibs/Maps/Japan_1984.cs
- ExtLibs/Maps/Japan_1988.cs
- ExtLibs/Maps/Japan_Lake.cs
- ExtLibs/Maps/Japan_Relief.cs
- ExtLibs/Maps/Japan_Sea.cs
- ExtLibs/Maps/Japan_Slopezone.cs
- Program.cs
The comment of #1964  was reflected.
Japan uses old roads. The latest satellite image hides in trees. Old images are useful.
· Japan: Contour map of Japan
· Japan_1974: Japan satellite image
· Japan_1979: Japan satellite image
· Japan_ 1984: Japan satellite image
· Japan_ 1988: Japan satellite image
· Japan_Lake: Japan's Lake Map
· Japan_Relief: color altitude map in Japan
· Japan_Sea: Chart of Japan
· Japan_Slopezone: Japan's slope map
> Map: Added Japan Maps

- GCSViews/ConfigurationView/ConfigArduplane.de-DE.resx
this is erroneously translated as "FS Werte" (=failsafe value), while it does set throttle slewrate (=Anstiegsrate)
> Fix plane basic tuning throttle slewrate field DE

- GCSViews/ConfigurationView/ConfigMotorTest.cs
When FRAME_CLASS = 2 is set, the MotorTest screen is disabled. The screen is displayed. But you can not operate it. I think that the motor test should be valid even when FRAME_CLASS = 2 (boat).
> MoterTest: add SURFACE_BOAT to if statement

- ExtLibs/ProjNet/CoordinateSystems/Ellipsoid.cs
My Windows is Japanese. The character of HORIZONTAL ELLIPSIS becomes the first byte of SJIS double-byte character and the double quote character is concatenated. This concatenation results in a build error.
I changed "..." to "." In three expressions.
> Fix garbled characters in HORIZONTAL ELLIPSIS

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
if not awaited Task.Delay returns inmediately and that is not its intended use. Thousands of Tasks/Timer objects could potentially be created with unexpected consecuences.
> Replaced unawaited Task.Delays with Thread.Sleep. 

- ExtLibs/Utilities/LogOutput.cs
Fix log->param extraction files to be CSV (comma) instead of TSV (tab)
> Fix log->param extraction files to be CSV instead of TSV

- GCSViews/FlightData.cs
If vehicle do not have GPS or stay indoor, its log will have 1980-1-1 timestamp. It would be helpful that mission planner can send system_time to vehicle, so that its log have current GCS timestamp.
> flightdata: add system_time action

- MainV2.cs
another solution would be to use RuntimeInformation.IsOSPlatform(OSPlatform.Windows) but that bring another dependency
> Update MainV2.cs to correctly check for windows XP

- ExtLibs/Maps/WPOverlay.cs
I often set the lat=0 and lon=0 of waypoint to hold the current location.
but I am not happy that the location of (0, 0) is displayed on the map.
Before
After
> Do not display waypoints with lat and lon 0

- GCSViews/FlightPlanner.cs
If I move waypoints using drag & drop in Flight Planner screen, the delay (1st param) is reset.
This PR allow to maintain the delay value.
> keep the delay value of a waypoint when moving

- ExtLibs/Utilities/DashWare.cs
- temp.cs
short packets dont get trailing commas out to the max column number...so those columns get interpreted by Dashware as ZEROS instead of nulls
@Hwurzburg Could you test this fix?
> DashWare: add trailing commas to csv file

- Program.cs
Due a setup problem (which fixed meanwhile) , if somebody want to use GeoCoding in MP (ZoomTo)  they need their own API key. This line adds a GoogleApiKey parameter to config.xml. If key not found then the original key used.
> Add possibility to use own GoogleAPI key

- GCSViews/FlightData.cs
Let the Set Mode dropdown in FlightData/Actions retain selected value if not clicked in, instead of go back to stabilize every time.
> Set Mode dropdown fix

- Joystick/JoystickSetup.cs
This is fix for the joystick window that loads button settings from xml file correctly but when it generates drop down controls it has a bug and always shows -1 for the button and ChangeMode for operation. This fixes both.
> Fixed joystick window not loading saved joystick buttons settings.

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
STATUSTEXT severity is a MAV_SEVERITY only if cs.version >= 0.4. This check always fails for sub-components, because they never send an AUTOPILOT_VERSION message. This means high-priority STATUSTEXT messages from sub-components are not sent to the HUD.
Fix this by comparing the "current" component version to 0.4 instead.
> fix sub-component statustext severity

- ExtLibs/Controls/HUD.cs
- GCSViews/FlightData.cs
- MissionPlanner.sln
Make coloring of HUD battery values honor BATT_LOW and BATT_CRIT settings.
If params are not set, then it fall back to speech warning values as it is originally.
-PS. It seems that VS needs two mono projects added to sln for build correctly, I put these in a separated commit
> Hud battery warning honor BATT_LOW and BATT_CRT parameters

- ExtLibs/Utilities/Settings.cs
- MainV2.cs
With this one can create different shortcuts for different vehicles with the same Mission Planner installation.
format is -config filename.xml where the extension must be .xml. The specified config file will be created from actual config.xml in the same directory.
Default config file is still config.xml
> Add -config command line option for defining alternative config file

- Plugin/Plugin.cs
- Plugin/PluginLoader.cs
- Plugin/PluginUI.Designer.cs
- Plugin/PluginUI.cs
- Now plugins are identified by their source filename (either .dll or .cs)
- Removed Dynamic Plugin loading from PluginUI, a restart will do it more easily.
> PluginManager: Update PluginManager to handle runtime compiled plugins

- MainV2.cs
Do not call loop() for plugins with zero loop rate.
(Currently loopratehz=0 causing call to loop() at every check.)
> [Plugin thread]: fix looprate 0

- MainV2.cs
To allow Main form title manipulation from a plugin (and keep the changed title on connect) titlebar should be public
> MainV2: Make titlebar public

- GCSViews/FlightData.Designer.cs
Remove double declaration of 'tableLayoutPanel2'  in FlightData.Designer.cs (It broke designer view in VS)
> FlightData.Designer: Remove double declaration of tableLayoutPanel2

- ExtLibs/Utilities/DFLog.cs
In case of non-gps navigation, there is no GPS log.
The trajectory of POS is disappeared by selecting item
It appeared after my change.
> use "POS" data to draw map

- Controls/MAVLinkInspector.cs
I changed the unit from "bit per second" to "bytes per second".
> MAVLinkInspector: fix the unit of bytes per second

- GCSViews/SITL.Designer.cs
- GCSViews/SITL.cs
- GCSViews/SITL.resx
As per Tridge's request to skip downloading of SITL binaries
https://github.com/ArduPilot/MissionPlanner/issues/2518
(also adjusted tab order of controls)
> Added checkbox "Skip Download"

- ExtLibs/Controls/QuickView.cs
- ExtLibs/Utilities/Warnings/CustomWarning.cs
- ExtLibs/Utilities/Warnings/WarningEngine.cs
- GCSViews/FlightData.cs
- MainV2.cs
- Utilities/ThemeManager.cs
- Warnings/WarningControl.cs
- Warnings/WarningsManager.Designer.cs
This update extends the WarningEngine with a new type of warning, where it changes color of the QV item background if condition is met.
I find it useful with QuickView's where there are a large number of items. 
It also goes well with the next upcoming patch which makes QuickView Tab undockable, for multi monitor GCS setups.
> WarningEngine: Add new type warning to color QV item backgroung

- GCSViews/FlightData.Designer.cs
- GCSViews/FlightData.cs
- GCSViews/FlightData.resx
It was needed for a multi screen GCS setup, I think it could be useful for others as well.
It goes with the previous PR, which adds QuickView items background coloring to WarningEngine.
> Make QuickViewTab undockable

- ExtLibs/Maps/GMapMarkerRect.cs
- GCSViews/FlightData.cs
- GCSViews/FlightPlanner.cs
I can't set a value of centimeters for the WAY point radius in the flight planner.
I can set the centimeter value in the config parameter.
I would like to be able to set a floating value.
> Global: Set the way point radius to a floating value

- GCSViews/ConfigurationView/ConfigUserDefined.cs
I found out that there is no option for RC15 and RC16 in the user parameters.
I made it possible to set the options for RC15 and RC16.
AFTER:
BEFORE:
> GCSViews: Add options for RC15 and 16

- Controls/ConnectionControl.resx
I found that some of the localized strings of "Link status" were displayed.
I resized it so that all the localized strings could be displayed.
> Controls: Show the full link status string

- ExtLibs/Mavlink/Mavlink.cs
- ExtLibs/Mavlink/message_definitions/ardupilotmega.xml
- ExtLibs/Mavlink/message_definitions/common.xml
- GCSViews/ConfigurationView/ConfigArducopter.Designer.cs
- GCSViews/ConfigurationView/ConfigArducopter.cs
- GCSViews/ConfigurationView/ConfigArducopter.resx
In the last few releases, several new filter values have been added, including notch and harmonic filters and FLT* filters. I have updated the UI to include fields for all those filters so that they don't need to be modified from the the parameter list or tree views.
> Updated Config -> Extended Tuning to include new filter values

- ExtLibs/Mavlink/MAVLinkMessage.cs
`processBuffer()` is called twice during  MAVLinkMessage construction
In
https://github.com/ArduPilot/MissionPlanner/blob/dc9f3fb4836f585ecbb35f12fa41dd1fa1ecccd3/ExtLibs/Mavlink/MAVLinkMessage.cs#L152
The setter already call `processBuffer()`
https://github.com/ArduPilot/MissionPlanner/blob/dc9f3fb4836f585ecbb35f12fa41dd1fa1ecccd3/ExtLibs/Mavlink/MAVLinkMessage.cs#L19
> remove redundant processBuffer call

- ExtLibs/Xamarin/Xamarin/Resources/mavcmd.xml
- mavcmd.xml
Trivial change to the DO_CHANGE_SPEED command table headers.
This resolves issue: #454
The table headers are now better aligned to both Mavlink Common descriptions and AP Stable and later.
> Correct the table headers for do_change_speed params

- ExtLibs/Utilities/Grid.cs
- Grid/GridData.cs
- Grid/GridUI.Designer.cs
- Grid/GridUI.cs
- Grid/GridUI.resx
ClipperLib defaults to counterclockwise polygon output.  This code allows the user to reverse some or all laps, starting with the perimeter.  Optionally, there is a selection to "fix" the first leg so that it follows the input polygon exactly.
See video demo here:
https://www.youtube.com/watch?v=s-L2RhRnsXg
> Allow clockwise spiral grid patterns

- GCSViews/FlightPlanner.cs
Undo function in Flight Planner was broken. This fixes: undo new wp, undo move wp or home point, undo split, undo move wp in grid, add below in frid.
> Fix FlightPlanner CTRL-Z undo

- Common.cs
- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
MAV_TYPE.COAXIAL was not handled in MavlinkInterface.cs, therefore not mode names were displayed.
GMapMarker type selection order also needed to change to keep the coax copter icon.
> fix coax and single copter firmware type setting

- ExtLibs/ArduPilot/CurrentState.cs
CurrentState.cs: Display the hygrometer message on the MissionPlanner.
https://user-images.githubusercontent.com/69180601/130919113-c7a43e44-ac16-4ee4-b514-39e14ba52f1f.mp4
> Display hygrometer message

- Grid/GridUI.cs
Camera footprints are not displayed if we don't have valid home altitude. This patch change startalt to PlannedHomeLocation.Alt.
Now footprints are shown again :)
> Grid: Use PlannedHomeLocation altitude

- GCSViews/FlightPlanner.cs
> GCSViews: If the delay of WAYPOINT is set to less than 0, set it to 0

- ExtLibs/Mavlink/MAVLinkParamList.cs
- GCSViews/ConfigurationView/ConfigHWCompass2.cs
My first go a `C#`, so apologies if this is a bit of a mess. 
This adds support for the new compass params names proposed in https://github.com/ArduPilot/ardupilot/pull/19123 and allows both new and old to work as before.
> GCSVews: Configuration: Compass2: support new compass param names

- GCSViews/ConfigurationView/ConfigRawParams.cs
This allows params to be entered as basic math expressions in the full list.
`1+2`, `5*10`, `8/9` ect
Brackets work, but not constants, powers or trig.
We could do more complex expressions if we were to add a math parser sub-module, but this gets us 99% of what anyone will use, and sub-modules are above by C# skill level.
> Config: Full Parameter List: allow math expressions

- GCSViews/FlightPlanner.cs
User needs to drag and move the map to see its change about grid after the 'Grid' check-box is clicked except for the first click, which may bother users with mild obsessive-compulsive disorder like me.
> update the map immediately once click 'Grid' check-box in FlightPlanner pannel

- GCSViews/ConfigurationView/ConfigFlightModes.resx
The wording of the Super Simple Mode display is missing.
I have changed it to show everything.
AFTER
BEFORE
> ConfigurationView: Show all text

- GCSViews/FlightPlanner.cs
Prevent creating an UNKNOWN first entry when a rally or a fence waypoints file is loaded.
discussed at https://discuss.ardupilot.org/t/geofence-file-cannot-be-saved/78871/13
> remove first (home) cmd when loading saved fence or rally from file.

- GCSViews/ConfigurationView/ConfigRadioInput.Designer.cs
- GCSViews/ConfigurationView/ConfigRadioInput.cs
Fix for ISSUE #2714.
On Radio Calibration Screen, the reverse checkboxes now honor RCMAP setting.
Also channel number is displayed in roll/pitch/yaw/thr bars.
> Fix for ISSUE #2714, Radio Calibration Screen reverse CB does not honor  RCMAP setting.

- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.resx
- GCSViews/ConfigurationView/ConfigRawParams.Designer.cs
- GCSViews/ConfigurationView/ConfigRawParams.cs
- GCSViews/ConfigurationView/ConfigRawParams.resx
- GCSViews/ConfigurationView/ConfigRawParamsTree.Designer.cs
- GCSViews/ConfigurationView/ConfigRawParamsTree.cs
- GCSViews/ConfigurationView/ConfigRawParamsTree.resx
A new Planner setting checkbox called "Running on a slow computer" controls how the ConfigRawParams and ConfigRawParamsTree pages are reloaded. If enabled, it keeps the metadata info and refreshes only the values and the control. For safety, there is a button to refresh the whole table (without reloading parameters from the vehicle).
Time improvements: Measured on an Intel Baytrail T Z3735F Quad Core stick computer with 2GB RAM 
original        Running on Slow Computer
ConfigRawParams reload        13sec                             2.4 sec
ConfigRawParamsTree reload  20sec                             3.5 sec
Note: Initial opening times of these pages are not improved; that needs a significant rewrite of the ParameterMetadataRpository, which is not in the scope yet.
> Speed up ConfigRawParams and ConfigRawParamsTree reload time

- Log/LogBrowse.cs
The LogBrowse ParamTreeView shows only the first param occurrence, which is recorded at the beginning of logging. The fix iterates through param log entries and keeps only the latest value of every param. This solves ISSUE #2758. 
**Note!, if there are multiple flights in the same log and the user changes param value between flights, the value shown will be the last one, which can be misleading looking at flights at the beginning of the log file.**
Also, fix the graph x-axis name issue when it changes back to "Line Number" at log file load, regardless of the Time checkbox state.
And a similar issue in the MAP when waypoints were moved or changed during logging ISSUE #2711
> LogBrowser: fix issue #2758, changed param values now shown in ParamView

- Controls/MavCommandSelection.Designer.cs
- Controls/MavCommandSelection.cs
- Controls/MavCommandSelection.resx
- GCSViews/FlightPlanner.cs
- MissionPlanner.csproj
- temp.Designer.cs
- temp.cs
- temp.resx
This one is for the Devs. A quick editor enables users to add mavlink commands to the dropdown list of the Planner grid. You can add commands that are already defined in MAV_CMD enum and new ones as well. Also, you can edit the param names that are displayed In the header.
The commands are stored in config.xml.
Adding a command here does not mean that the autopilot will accept or execute it. So the user has to know what is he/her doing.
> CTRL-F screen, add editor to add/delete mavlink commands to Planner grid dropdown

- GCSViews/FlightPlanner.cs
I discovered that my home position was in the sixth decimal place.
The ArduPilot is valid to the seventh decimal place.
I increased the digits to the seventh decimal place.
> GCSViews: Set the home position to the seventh decimal place

- Grid/GridPlugin.cs
Toolstrip menu item is also created in FlightPlanner.
> Grid: Remove duplicated ToolstripMenu item creation.

- GCSViews/FlightData.cs
Fixes https://github.com/ArduPilot/MissionPlanner/issues/2346
Currently custom named value floats work great, thanks to https://github.com/ArduPilot/MissionPlanner/pull/2360. However, they get added to the graph on reload but do not get added to the list of tick boxes. This means it is not possible to remove a named float from the graph unless it is currently being received. This stores both the name and key in the "selected" string so on reload the item gets added to the graph and tick boxes. The graph will then start displaying values as soon as they a received.
> GCSViews: FlightData: persist namedfloat over re-load

- Common.cs
Fix for ISSUE #2771
The annoying "New Firmware available" pop-up at the startup now disappears when the checkbox "Show me again" is unchecked.
> Fix for ISSUE #2771, New Firmware available "Show me again" checkbox does not work

- ExtLibs/Utilities/Settings.cs
In Linux/Unix like operating systems 'MyDocuments' dir does not exists.
However, the mono framework for compatibility purposes points it to the root of the user directory instead(/home/username). That is incorrect from the point of view of the Linux/Unit standards (see [1] for more detail). The Local Application
Data directory should be used instead(/home/username/.local/share). Fix that for operating systems where platform ID is Unix.
* [1] https://www.freedesktop.org/wiki/Specifications/basedir-spec/
Please be aware for existing users it might be required to execute a command
```bash
mv "~/Mission Planner" ~/.local/share/
```
> Fix application local data path in *nix based OS

- temp.resx
Change "regenerage" to "regenerate".
closes #2797
> Fix typo at setup->advanced

- GCSViews/ConfigurationView/ConfigBatteryMonitoring.cs
this is an attempt to get rid of these errors when using an I2C battery monitor, which doesn't have the multiplier params:
tested successfully in both SITL and with Pixhawk5X with I2C battery monitor
> suppress errors when not analog battery monitor

- mavcmd.xml
The following discus says that the MAV_CMD_NAV_SCRIPT_TIME message is not in the plan's command list.
I have added it to the command list.
https://discuss.ardupilot.org/t/copter-4-2-and-fast-descent/83565
MAV_CMD_NAV_SCRIPT_TIME SPEC:
https://mavlink.io/en/messages/ardupilotmega.html#MAV_CMD_NAV_SCRIPT_TIME
AFTER
PLAN FUNCTION
PLAN FILE
> PLAN: Add MAV_CMD_NAV_SCRIPT_TIME to the command list

- ExtLibs/px4uploader/Firmware.cs
- ExtLibs/px4uploader/Uploader.cs
- Utilities/Firmware.cs
Allow the flashing of external flash images to boards with external flash
Tested on an SPRacingH7
> Fix bugs in external flash flashing

- GCSViews/FlightData.cs
Seeing these separate conditional makes me think that ArduCopter has a different name for "Loiter" than the other firmwares but that's not the case.
Is there another reason why we want to split the conditional into two?
> Remove confusing conditional

- ExtLibs/Maps/WPOverlay.cs
I learned that the WAY POINT radius drawing shows in meters.
I draw the WAY POINT radius in floating values.
By RTK, the positioning error is in centimeters.
AFTER：
> ExtLibs: Draw the WP radius as a floating value

- GCSViews/FlightPlanner.cs
fix this issue
https://discuss.ardupilot.org/t/how-delete-tracker-home-point/69980
TrackerLocation returns HomeLocation here.
https://github.com/ArduPilot/MissionPlanner/blob/master/ExtLibs/ArduPilot/CurrentState.cs#L1293
Tracker Home is often displayed because PlannedHomeLocation and HomeLocation are different.
This PR changed to compare TrackerLocation and HomeLocation to judge displaying "Tracker Home".
> FlightPlanner: do not display tracker home when same as home location

- Plugins/example16-donate.cs
I would like the Mission Planner to be neutral.
I think that donations to Ukraine should be collected on Facebook at CUBEPILOT .ORG.
I have responded not to show.
AFTER:
> Plugins:Make the Mission Planner neutral

- ExtLibs/ArduPilot/CurrentState.cs
- ExtLibs/Xamarin/Xamarin/GCSViews/FlightData.xaml.cs
- ExtLibs/Xamarin/Xamarin/GCSViews/WinForms.xaml.cs
- ExtLibs/Xamarin/Xamarin/Linked/MainV2.cs
- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.resx
- MainV2.cs
This adds a check box to enable speech only when armed. 
Speech is very useful, but somewhat annoying when disarmed, log download for example will often result in a few pre-arm warnings that will get announced. I mute the PC to avoid this but then often end up forgetting to un-mute again for the next flight. 
My first go at "GUI" stuff in MP. 
I suspect the `Xamarin` stuff is wrong, it seems it is not used for the windows build? How can I test?
> Add speech armed only option

- ExtLibs/ArduPilot/CurrentState.cs
Request from ArduPilot Partner
This allows the HUD to report voltages greater than 65V. This limitation comes from the mavlink fields only being uint16s.
In ArduPilot we fill the cell fields to overcome this deficiency even if the monitor type doesn't report cell voltages.
I'm not sure how to make this compatible with systems not reporting the `battery_status` message. But I'm not sure  how old that message is or how important compatibility is with systems not reporting battery_status?
I think the battery2 message isn't used anymore as well?
> ArduPilot: State fix Battery Voltage Reporting for Batts >65.5V

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
Certain radio configs (esp Serial/Ethernet bridges) do not play well with mavlink bursts; for a temporary solution with this setting, it is possible to force back to old-fashioned parameter download.
> Add a Setting to force old style params download (no MavFtp)

- ExtLibs/ArduPilot/CurrentState.cs
needed for octoquad quadplanes which typically use outputs 5 to 12
> support ESC 9 to 12

- ExtLibs/ArduPilot/CurrentState.cs
supported with SERVO_32_ENABLE=1 in ArduPilot 4.3
> support 32 servo display

- mavcmd.xml
This resolves two minor issues that I've raised recently
- https://github.com/ArduPilot/MissionPlanner/issues/2876
- https://github.com/ArduPilot/MissionPlanner/issues/2864
I have lightly tested this and the commands appear in the correct place.  The only issue is that Mavlink.cs doesn't contain ATTITUDE_TIME=42703 on my machine but I suspect a proper re-build using the latest ArduPilot/mavlink will resolve this.
> mavcmd: move SCRIPT_TIME up and add ATTITUDE_TIME

- mavcmd.xml
I don't think indentation is necessary unless the DO_AUX_FUNCTION command needs to be emphasized with indentation.
Indentation for other commands is whitespace.
The indent for this command is tabs.
> Change the indentation of DO_AUX_FUNCTION

- ExtLibs/Utilities/dfgpslag.cs
I want to reduce the build warnings.
I set null to 0, because I want the return value to be a number.
> ExtLibs: Change the judgment value

- mavcmd.xml
This adds the new DO_GIMBAL_MANAGER_PITCHYAW command to the list of available mission commands.  Support for this command is being added to the flight code with PR https://github.com/ArduPilot/ardupilot/pull/20915 which will likely be merged within a week.
This has been lightly tested in SITL and seems to work OK.  There is still the issue of Param5 (aka "x") being corrupted but this is an existing issue that also occurs for ATTITUDE_TIME.
> mavcmd: add DO_GIMBAL_MANAGER_PITCHYAW command

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
Similar to the fix for issue https://github.com/ArduPilot/MissionPlanner/issues/2885 we should not be scaling the "x" field.
I'm not actually able to build and test MP on my machine but I think this should work.
> MAVLinkInterface: scale DO_GIMBAL_MANAGER_PITCHYAW

- GCSViews/ConfigurationView/ConfigBatteryMonitoring.resx
MONITOR was displayed in MONITO.
I changed the layout.
AFTER
BEFORE
> ConfigBatteryMonitoring: Change missing item string

- ExtLibs/ArduPilot/CurrentState.cs
Fixes HIGH_LATENCY messages to place air_temperature fields into air temperature and not IMU temperature
Adds air_temperature fields
Adds a note so so that handling of SENSOR_OFFSETS can be removed in the future
Renames IMU_Temperature fields: I think we should standardize around the idea of `INSTANCE1_sensor`  `INSTASNCE2_sensor`
Not IMU_Temp1,  IMU_Temp2   ....  
The first IMU doesn't have three temperature sensors ... 
I realize there are a lot of fields listed the other way and a few the way I'm suggesting.
BTW thanks for adding the IMU temperatures. I didn't notice you fixed it until I tried to rebase on master. That is when I saw the difference in naming ;)
> ArduPilot: Temperature Reporting

- GCSViews/ConfigurationView/ConfigFlightModes.cs
I have an inexpensive radio that supports 16 channels.
ArduPilot supports up to channel 16.
I allow up to channel 16 to be assigned as a flight mode switch.
AFTER
> GCSViews: Allow flight mode channels up to channel 16

- mavcmd.xml
This PR makes a few changes primarily to the Rover command list (there is one change to the Plane list)
- alphebetise the rover command list.  Like Copter's list the nav commands appear at the top with the two most common commands (WAYPOINT and RETURN_TO_LAUNCH) appearing right at the top.  Other less popular nav commands are then in alphabetical order.  "do" and "conditional" commands are next and are all in alphabetical order.
- removed unsupported do-set-home
- removed unsupported do-mount-configure from both rover and **plane**'s lists.
- added titles to the do-digicam-configure and do-digicam-control messages (for rover)
- removed unsupported arguments from do-change-speed (for rover)
I have tested this on my local machine by copying the mavcmd.xml and confirming the commands appear …
> MavCmd: alphebetise and fixup rover command list

- GCSViews/ConfigurationView/ConfigPlanner.resx
There is an indication that the checkboxes for speech selections are collapsed.
I would change the layout to show the checkboxes.
AFTER
BEFORE
> ConfigrationView: Change Speech's checkbox display

- GCSViews/FlightData.Designer.cs
- GCSViews/FlightData.resx
- MissionPlanner.csproj
- Plugins/example21-persistentsimple.cs
This adds an empty, zero-sized panel between the HUD and the tabs. This allows for the creation of plugins that add buttons or readouts that are always visible, and don't require clicking around through tabs.
As an example of how this could be useful, I have included an example .cs plugin in this pull request (disabled by default), similar to tabActionsSimple, with three mode switch buttons. The three modes can be changed to anything by simply tweaking three lines in the .cs file without having to rebuild anything.
> Add empty persistent panel between HUD and tabs

- Common.cs
- GCSViews/ConfigurationView/ConfigADSB.cs
- GCSViews/ConfigurationView/ConfigFriendlyParams.cs
- GCSViews/ConfigurationView/ConfigOSD.cs
- GCSViews/ConfigurationView/ConfigRawParams.cs
- GCSViews/ConfigurationView/ConfigRawParamsTree.cs
Allows to skip the "DON'T DO THIS IF YOU ARE IN THE AIR" warning on param refresh. Currently:
With this change:
Skip box works as expected.
> Param refresh: add show again check box

- ExtLibs/ArduPilot/CurrentState.cs
Display units for horizontal and vertical accuracy.
Items without units were recognized as index values.
I learned that they are units of meters.
I shortened the item name because it was long.
> ExtLibs: Display units for horizontal and vertical accuracy

- ExtLibs/ArduPilot/CurrentState.cs
- GCSViews/FlightData.cs
- MainV2.cs
The basic issue is that we need to support a much larger set of NAMED_VALUE floats. They are very useful in LUA scripts for telemetry.
This is a terrible design pattern, but it was useful for a partner and it might be useful for others until the pattern can be changed to be less copy & paste of the same pattern? (I only had a very short turnaround on this one. So doing it properly by refactoring heavily was not in the cards.)
I will let you decide Michael the utility of this?
> Add 10 more named floats

- GCSViews/FlightPlanner.cs
I am unclear about the "-" separator in the altitude display in guided mode and the "-" for relative altitude below 0 meters.
I see "-50" for 50 meters relative altitude.
I changed the "-" to ":" to clarify.
AFTER
BEFORE
> GCSViews: Change the delimiter

- MainV2.cs
I made changes to #2902.
I have learned that ConnectionControl is mobile before the UI language is set.
I made the UI language setting before the initialization of ConnectionControl.
AFTER
1. UI LANG IS English
2. UI LANG is Japanese
3. UI LANG is Korean
> ConnectionControl: Link status display string with UI language specification

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
- GCSViews/FlightData.cs
This auto reconnects after a sending a reboot command, useful when doing initial setup where lots of reboots are needed. Also handy for catching very early start up messages. 
Testing:
- direct USB reconnects
- USB telemetry does not reconnect because the link is not closed
- TCP to SITL does not reconnect (it would be nice to get this working in the future, maybe SITL does not close the link correctly)
- firmware upload works as normal
> Reboot: auto reconnect

- GCSViews/ConfigurationView/ConfigMount.cs
The other parameter names are group and item names.
I want the group name and the item name.
This change will be an obstacle when supporting MNT2.
AFTER
> ConfigMount: Change to group and item names

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
- ExtLibs/Utilities/locationwp.cs
- mavcmd.xml
this fixes extra 2 args on SCRIPT_TIME and fixes several WP types for MAVFtp
> MAVLink: allow more args to SCRIPT_TIME

- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
I sometimes let them fly for more than 40 minutes.
MP takes about 10 minutes and erases from the old track.
I would like to see the flight trajectory to verify the actual flight.
I change the max track length from 2000 to 200000.
AFTER
> ConfigPlanner: Ensure flight trajectory does not disappear for more than 1 hour

- ExtLibs/ArduPilot/CurrentState.cs
We store the firmware type of the last connected vehicle in config.xml, but to my knowledge, nothing actually checks that setting. This changes that. This will allow people who solely operate, for example, ArduPlane, to plan missions before being connected to the bird or to a SITL instance.
Additionally, this should provide a workaround for those being plagued by #2904. It doesn't resolve the underlying issue, but fixes the symptom for those not frequently switching vehicle types.
> CurrentState:init with APMFirmware config.xml

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
- ExtLibs/Utilities/DisplayView.cs
- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.resx
I set the voice notification and HUD display level to NOTICE or higher.
There are some messages I would like to be notified about in the voice notification and HUD display.
I know that I am voice notified of NOTICE or above in QGC.
ArduPilot is notifying me of NOTICE level messages.
I think there is merit to have this message displayed on the HUD, with voice notification.
Other:.
The message display on the HUD uses red, yellow, and white colors to distinguish between emergency, warning, and other.
> Set the low level of SEVERITY to speak

- GCSViews/ConfigurationView/ConfigRadioOutput.cs
Allows configuration of the full 32 servos from the Servo Output page if enabled.
> GCSViews: Configuration: RadioOutput: allow upto 32 servos if  enabled

- GCSViews/ConfigurationView/ConfigPlanner.resx
Item strings "Enable HUD Overlay" were partially hidden.
I show this string.
AFTER
BEFORE
> ConfigurationView: Display all item strings

- GCSViews/SoftwareConfig.cs
The flight mode settings are located on the Setup and Configure screen.
I would prefer one screen.
I removed it from the config screen.
AFTER
BEFORE
> FlightMode: Set flight mode setting to setup only

- README.md
users need to run git submodule init
clarify which menu item should be used to build
> README: clarify build instructions

- ExtLibs/Utilities/ParamFile.cs
ensures users don't load old calibration values
> param: fixed exclusions for change of GND_ params to BARO params

- GCSViews/ConfigurationView/ConfigMount.cs
- GCSViews/ConfigurationView/ConfigMount.designer.cs
- GCSViews/ConfigurationView/ConfigMount.resx
This is a small enhancement to the mount setup page to fix up two very obvious problems.  This is a subset of this larger PR https://github.com/ArduPilot/MissionPlanner/pull/3013.  This doesn't allow this page to be used for the stable releases (4.3).. this will come in a follow-up PR.  I created this small PR in the hopes that it would be easier to review and merge.
1. remove the CONTROL_X/Y/Z section (these parameters haven't existed for years)
2. remove the STAB_PAN parameter checkbox.  Users should never be setting this parameter so it is best that we just remove it.
This has been tested on my PC connecting to a Pixhawk1 running Copter-4.2.3.
> ConfigMount: remove Control and Pan stabilize controls

- ExtLibs/Controls/MyButton.cs
- Utilities/ThemeManager.cs
Add the ability to set a disabled button text color in a theme. For example
At the moment, this is a secret capability, just like button border color currently is. It has to be manually added to the color theme text file by adding
```
<ThemeColor>
<strColorItemName>Disabled Button Text</strColorItemName>
<clrColor Web="#5C5C5C" />
<strVariableName>ButtonTextColorNotEnabled</strVariableName>
</ThemeColor>
```
If the color is not set in the theme, it defaults to the button text color.
Alternatively, I'd be happy to amend the PR to fully integrate this to the existing themes and add button border color to them while I'm there.
> MyButton: add disabled text color

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
It looks like the purpose of this section of code is to put fake PARAM_VALUE messages in the tlogs to emulate what you would have seen in the tlogs before MAVFTP was implemented. If I'm interpreting that correctly, these messages should have the sysid/compid of the source of the FTP param file. 
This fixes the ability to extract params from tlogs, which has been broken since MAVFTP was implemented (at least when doing it from MP's tlog graph tool).
It also fixes anything that relies on MainV2.comPort.MAV.param during log replay. Not sure if anything like that exists in the main code, but I encountered it while I was working on a plugin.
> MAVFTP params: use MAV's sysid/compid in tlog

- GCSViews/FlightPlanner.cs
The "Zoom To" search function in the Map Tool menu on the Flight Planner page does not work with Bing or Google map providers. I'd try others, but I don't know which providers work and which don't.
OpenStreetMap _does_ work though for these search requests ([despite not working for map tiles](https://operations.osmfoundation.org/policies/tiles/)). This temporarily switches the provider to OpenStreetMap, does the search, then switches back.
Alternatively, I'd support deleting this clearly rarely used feature, but now that I know it exists, and that it works now, I really like it.
> MapTool: use OpenStreetMap to zoom to locations

- Plugins/OpenDroneID2/OpenDroneID_Plugin.cs
- Plugins/OpenDroneID2/OpenDroneID_UI.Designer.cs
- Plugins/OpenDroneID2/OpenDroneID_UI.cs
The basic ID is stored in the ArduRemoteID device in the current implementation. See for instance this PR: https://github.com/ArduPilot/ardupilot/pull/22447 Therefore the basic ID check can be removed from the Drone ID plugin.
This PR 
- removes the check / LED for entering an UAS ID.
- add information text to the UAS ID tab and Operations tab. Basically it tells the user that these fields are optional (for the USA).
> RID plugin: remove UAS ID check

- ExtLibs/Controls/HUD.cs
Someone pointed out this behavior on Discord.
> HUD: use nofix icon for "no fix" instead of nogps

- ExtLibs/Comms/CommsNTRIP.cs
If a user's ntrip username or password has special characters (not letters or numbers), ie ``http://user1#:938aasd^!@ntrip.data.gnss.ga.gov.au:2101/TEST1`` the URI string will not be properly encoded.
This PR allows for these special characters to be used, which is useful as some NTRIP providers are now enforcing password policies of requiring special characters.
> ExtLibs: Allow for special characters in NTRIP connection string

- GCSViews/ConfigurationView/ConfigFirmwareManifest.cs
Fixes an issue that Alex/ARACE pointed out on Discord. There are circumstances where someone might want to upload custom firmware with a computer that has no internet access at the time.
> ConfigFirmware: allow offline access to certain parts

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
With more configurable types it is harder to tell the vehicle firmware type from the mavlink type enum. This changes to use the version string if it is available. 
For example on a fresh setup there is no frame class setup, so it defaults to generic and then we endup with no param descriptions or mode names.
> ExtLibs: ArduPilot: Mavlink: try and pull AP firmware type from version string

- GCSViews/ConfigurationView/ConfigHWCompass.cs
- GCSViews/ConfigurationView/ConfigHWCompass2.cs
some users were putting in a magnetic heading
> magcal: note that heading is true, not magnetic

- ExtLibs/ArduPilot/LogMetaData.cs
- Log/LogBrowse.cs
This adds support for parsing bitmask masks from the logmetadata xml and applying them to values. So you can plot each bit field individualy. Currenlly the TECS message is the only example in the xml, because of this I have not tested instance with bitmask, but it should work.
As a byproduct we also now get mask with `&` as a manual modifier too. The modifiers also are included in the label, for example:
We need to update the log meta data a little to give a name and description for each bit. I would also like to give a mask rather than a bit so we can do multiple bit values (there are some in the EKF I think). Maybe we should do that metadata rework before merging this, @peterbarker any thoughts?
> Log review: support bitmask fields from metadata

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
This fixes a issue where param fetch can get stuck if there are no missing params between the start index and the total number of params. This can happen if a specific request fails.
This also skips the 4 second wait before retry if we got the last param but are still missing some.
Also will keep re-trying a list request if param count is still 1 because no params have been received.
> ArduPilot: MavLink: Param fetch: fix getting stuck with missing params

- Log/LogBrowse.cs
If log's instance is not integer, exception happens.
So I change to use int.TryParse instead of int.Parse.
Before
After
The log output here will have a char type in the instance.
https://github.com/ArduPilot/ardupilot/blob/Copter-4.3/libraries/GCS_MAVLink/GCS_Common.cpp#L3179
> LogBrowse: use int.TryParse instead of int.Parse

- ExtLibs/Xamarin/Xamarin.Android/Xamarin.Android.csproj
Fixes Android build
I am not sure why the action for this only recently started failing, but this fixes it.
> Xamarin: change http handler

- ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/GMapProvider.cs
I got System.FormatException when using Mapbox service.
I confirmed it worked after adding this condition.
> GMapProvider: add Empty check for RefererUrl

- Controls/SerialSupportProxy.Designer.cs
- Controls/SerialSupportProxy.cs
- Controls/SerialSupportProxy.resx
- GCSViews/ConfigurationView/ConfigAdvanced.Designer.cs
- GCSViews/ConfigurationView/ConfigAdvanced.cs
- GCSViews/ConfigurationView/ConfigAdvanced.resx
- MissionPlanner.csproj
See https://github.com/ArduPilot/MissionPlanner/issues/3062
@tridge, any comments on the names and descriptions in that screenshot?
> ConfigAdvanced: add support.ardupilot.org proxy

- mavcmd.xml
This adds 5 commands to the mission list for Plane, Copter and Rover.  Support for these commands will be added in AP 4.4 (see https://github.com/ArduPilot/ardupilot/pull/23147).
- [MAV_CMD_SET_CAMERA_ZOOM](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1507) <-- only continuous type (not step or position yet)
- [MAV_CMD_SET_CAMERA_FOCUS](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1515) <-- only continuous type (not step or distance yet)
- [MAV_CMD_IMAGE_START_CAPTURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1544) <-- only takes 1 picture
- [MAV_CMD_VIDEO_START_CAPTURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1584)
- …
> mavcmd: add image start capture

- ExtLibs/ArduPilot/Mavlink/MAVFtp.cs
the RFD900x with multipoint can't handle over 80 byte data size for FTP
this needs some testing before merge
fixes issue #3086
> MAVFTP: use smaller read/write sizes to keep radios happier

- GCSViews/ConfigurationView/ConfigRawParams.cs
Parameters that have both of these need a character to break them up.
Before
After
> ConfigRawParam: handle range and value together

- mavcmd.xml
AP 4.4.0 (and higher) includes support for the [JUMP_TAG](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1523) and [DO_JUMP_TAG](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1527) commands.
This PR adds these commands to the Plan screen's command list for Plane, Copter and Rover.  This has been tested in SITL for all three vehicles. 
I've placed the two commands just below the existing "DO_JUMP" command for all three vehicles.
Here's a screen shot of a Copter in SITL exercising the new commands.
FYI @magicrub
> mavcmd: add jump-tag commands for plane, copter, rover

- GCSViews/ConfigurationView/ConfigRawParams.cs
When editing a float param, the cell gets set to a double, instead of a string, which throws a typecase exception if the cell is edited and then "None Default" is clicked. I fix this on both ends, setting the cell to a string, and using `ToString` everywhere instead of typecasting.
The only part of this PR that is truly needed is the `ToString` on line 446, but it's too easy to make a similar mistake in the future and have it go unnoticed.
> ConfigRawParams: fix typecast exception

- GCSViews/ConfigurationView/ConfigRawParams.cs
This really should be clamped instead of checking and failing to min like I had it. The original version also failed when the value was equal to the max (should have been `<=` not `<`).
> ConfigRawParams: clamp numeric control

- ExtLibs/Utilities/Settings.cs
This adds a new GetDecimal() helper but also it ensures the default value is returned when a TryParse() fails in the various helpers.
Current code assumes ```TryParse(string, result)==false``` does not touch result because we are initially setting the result with the default value and then always return the value without checking the return boolean. However, the docs say it will trample on result when returning false. Here's the docs for Int32.TryParse()
```
//   result:
//     When this method returns, contains the 32-bit signed integer value equivalent
//     of the number contained in s, if the conversion succeeded, or zero if the conversion
//     failed. The conversion fails if the s parameter is null or System.String.Empty,
//     is not of the correct format, or represents a number …
```
> Fix getting settings default result

- Controls/SerialOutputCoT.Designer.cs
- Controls/SerialOutputCoT.cs
- Controls/SerialOutputCoT.resx
- ExtLibs/Utilities/Settings.cs
This PR does 3 things and also uses GetDecimal() from PR https://github.com/ArduPilot/MissionPlanner/pull/3103
- Changes UI send interval to any seconds you want from 1s to 9999s.
- Saves/loads all settings on the page
- allows graceful resuming UI-wise by stop/starting the thread (sort of) when window is closed and reopened. Before, the data was being sent but the textbox handler was invalid until the thread/button was stop/started.
> CoT: adds send interval and saves all settings

- ExtLibs/Controls/HUD.cs
- ExtLibs/wasm/Controls/HUD.cs
- GCSViews/FlightData.cs
- plugins/example9-hudonoff.cs
Three things:
- Don't always show HUD BATT2 if HUD BATT1 is shown.
- Don't override user setting to show HUD BATT. Respect the HUD user setting
- Allow HUD BATT2 a separate show enable
> HUD: Don't override user setting to show BATT, add BATT2 option

- Controls/ConnectionStats.cs
Comm Stats: reset button to clear all the fields better
Before this, they would actually just stop updating and another mavlink packet would show the new initial value.. but the old ones would still show if you were actually disconnected or lost link
> Comm Stats: reset button to clear all the fields better

- ExtLibs/Utilities/Settings.cs
This reverts commit 680f0715281f16ae34b2aa76e89ed6bae6d58deb.
PR https://github.com/ArduPilot/MissionPlanner/pull/3104 included a commit from https://github.com/ArduPilot/MissionPlanner/pull/3103 and when merged it did a duplicate commit to upstream. This reverts that extra one.
> Revert "Settings: add GetDecimal() to Settings.Instance storage"

- GCSViews/FlightData.Designer.cs
- GCSViews/FlightData.cs
- GCSViews/FlightData.resx
This allows the GCS from the FlightData screen to jump to a JUMP_TAG. This PR is on top of @rmackay9 's PR  https://github.com/ArduPilot/MissionPlanner/pull/3097 which adds it to the mission pulldown list
> Jump Tags - add ability to Trigger it

- MainV2.cs
The call to MainV2.comPort.sendPacket waits for MAVLinkInterface.objlock to release. This can cause a deadlock if the MAVLinkInterface thread has also called adsb_UpdatePlanePosition, and is waiting on this thread to release adsblock. adsblock is only needed for accessing the adsbPlanes list, so this commit restricts the lock to only where it is needed.
When constructing the mavlink packet, adsbPlanes and adsb are used a bit randomly. I changed those all to read from adsb, and moved them out of the locked section as well.
> ADSB: fix deadlock issue

- mavcmd.xml
This adds LOITER_TURNS to the rover command list.
The AP Rover flight code added support for LOITER_TURNS command as part of PR https://github.com/ArduPilot/ardupilot/pull/23890.
This has been tested on my local machine.
> mavcmd: rover command list gets LOITER_TURNS

- GCSViews/ConfigurationView/ConfigRawParams.cs
Displaying the options drop down for bitmask parameters makes it impossible to set more than one option. We should probably not have have both in the param meta data, but there are some with both currently. `PILOT_THR_BHV` is a example of this on copter. Currently it will display the drop down:
With this PR we now get the bitmask button.
> GCSViews: ConfigRawParams: bitmask takes priority over options

- mavcmd.xml
This renames the "On/Off" field of the DO_DIGICAM_CONTROL command to "Session Control" which better matches [the mavlink spec](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1226) and, I hope, will reduce confusion with the "Shutter Control" field which is what most users actually need to set.
This has been lightly tested on my desktop and the before and after shots are shown below.
BEFORE:
AFTER:
Thanks to @CraigElder for reporting this issue.
> mavcmd: update do-digicam-control fields

- ExtLibs/Utilities/GeoRefImageBase.cs
It seems that the Min Shutter field was intended to filter out all messages with too short of a shutter, but as written, it only removes the shortest one (also, there's a mix of using `minshutter` and a hard-coded `0.5`). I have instead changed it to a loop to remove all instances.
Additionally, I noticed that `dropend` got commented out, and uncommented it. I'm not sure why that was done, but it seems mistaken. Please confirm that there wasn't some really good reason for commenting that out.
> GeoRefImage: fix min shutter filter

- GCSViews/ConfigurationView/ConfigRawParams.Designer.cs
This messes with the param editor column widths to try and make resizing better. Param names and units change to a fixed width to fit everything ("AllCells").  This should mean that the other column's get more room when resizing. The "FAV" column is made none re-sizable, so it should stay small.
The remaining columns that can be changed are the value, default, options and description.
> GCSViews: ConfigurationView: update coloum width

- GCSViews/ConfigurationView/ConfigRawParams.Designer.cs
- GCSViews/ConfigurationView/ConfigRawParams.cs
We unwittingly introduced a search slowdown in https://github.com/ArduPilot/MissionPlanner/pull/3130. The auto column width is terribly optimized reruns any time a row's visibility is changed, and `SuspendLayout` isn't helping like I'd think it would.
To fix this, I have the auto width turn on and off. I changed the default column width mode for the entire data grid to `AllCells`, and changed the `NotSet` columns to `None`, and changed the `AllCells` columns to `NotSet`. Anywhere where `SuspendLayout` was being called, I added `Params.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;`, and restored the auto size wherever `ResumeLayout` was called (I actually implemented this in a helper function instead of copy/pasting that all 4 places).
We could also probably just go to fixed …
> ConfigRawParams: fix search slowdown

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
- GCSViews/FlightData.cs
- GCSViews/FlightData.resx
- MainV2.cs
This fixes three issues I've found with the Payload Control tab
- The tab appears/disappears based on whether a MAVLink enabled gimbal has been seen or not but most gimbals are not mavlink enabled meaning this tab is normally invisible at first.  I've removed the logic to show/hide this tab and instead it is left to the user to use the Customise checkboxes.
- The Roll scroll bar direction was reversed meaning a gimbal would roll in the opposite direction to what the user would expect
- MOUNT_CONTROL messages have been replaced by MAV_CMD_MOUNT_CONTROL commands.  This command has been accepted since 4.0 (perhaps much earlier).
This has been tested on my PC with a DJI RS2 gimbal ([see AP user wiki here](https://ardupilot.org/copter/docs/common-djirs2-gimbal.html)) running latest ArduPilot. …
> Flightdata, Payload Control tab fixes

- Plugins/OpenDroneID2/OpenDroneID_UI.cs
A recent rename of `CurrentState.MovingBase` to `CurrentState.Base` meant the OpenDroneID plugin failed to build. This PR fixes this.
> Fix as a result of rename

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
This changes the SetMountConfigure method so that it uses the [MAV_CMD_DO_MOUNT_CONFIGURE mavlink command](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1274) instead of the deprecated ardupilot specific [MOUNT_CONFIGURE message](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/ardupilotmega.xml#L1237).
This method is only used by the Payload Control tab's "Reset Position" button.
By the way, ArduPilot has consumed the do-mount-configure command since before ver 4.0 (I didn't look back any further than this).  Ardupilot stopped consuming the roll_stab, pitch_stab and yaw_stab values in version 4.3 but this PR doesn't change how these fields are set anyway.
This has been lightly tested on a real autopilot using a Xacti …
> ExtLibs: setMountConfigure uses mav-cmd-do-mount-configure

- ExtLibs/Comms/CommsNTRIP.cs
- GCSViews/ConfigurationView/ConfigSerialInjectGPS.Designer.cs
- GCSViews/ConfigurationView/ConfigSerialInjectGPS.cs
- GCSViews/ConfigurationView/ConfigSerialInjectGPS.resx
Casters using RTKLib are still using NTRIP V1.0 so a checkbox allow to support them
Tested with Centipede caster that use RTKLib, connexion string : 
http://caster.centipede.fr:2101/TCY22
I am not sure about the process to add a checkbox, I have use Visual Code designer to create the new box. We can probably use a failover mecanism to support both protocol without checkbox, but my skill on C# are low and the casters I have tested aren't refusing v2.0 string as they return http code 200 which is annoying ...
> CommsNTRIP: add a checkbox to select NTRIP v1.0 for older caster

- ExtLibs/AltitudeAngelWings.Plugin/AASettings.cs
- ExtLibs/AltitudeAngelWings.Plugin/MapAdapter.cs
- ExtLibs/AltitudeAngelWings.Plugin/OverlayAdapter.cs
- ExtLibs/AltitudeAngelWings/AltitudeAngelWings.csproj
- ExtLibs/AltitudeAngelWings/Clients/Api/Model/FeatureExtensions.cs
- ExtLibs/AltitudeAngelWings/Clients/Api/Model/FeatureProperties.cs
- ExtLibs/AltitudeAngelWings/IMap.cs
- ExtLibs/AltitudeAngelWings/IOverlay.cs
- ExtLibs/AltitudeAngelWings/OverlayFeature.cs
- ExtLibs/AltitudeAngelWings/OverlayFeatureType.cs
- ExtLibs/AltitudeAngelWings/Service/AltitudeAngelService.cs
* Reducing the memory used when displaying map features, particularly when thousands are returned from the API
* Large speed up of map rendering by processing all the map features as a batch instead of individually
* Improving the map cache locking to avoid exceptions during map updates, especially large ones
* Removing map code that is no longer used
* Improving the performance of Settings loading when large number of map features are present
* Memory profiling of the map feature components to further reduce memory load
> Optimizations and map display bug fixes

- ExtLibs/AltitudeAngelWings.Plugin/Resources/MapInfoDockPanel.html
- ExtLibs/AltitudeAngelWings/AltitudeAngelWings.csproj
- ExtLibs/AltitudeAngelWings/Clients/Api/Model/DisplayInfoExtensions.cs
- ExtLibs/AltitudeAngelWings/Clients/Api/Model/FeaturePropertiesExtensions.cs
- ExtLibs/AltitudeAngelWings/ISettings.cs
- ExtLibs/AltitudeAngelWings/ServiceLocatorConfiguration.cs
- ExtLibs/AltitudeAngelWings/Settings.cs
Adding the display of Legacy, UTM Basic (notify), and UTM Ready (connected) airspaces. This enables a better understanding of when approval is needed for the use of airspace and if that approval is fully electronic, simple electronic notification, or legacy phone contact based. See https://www.altitudeangel.com/news/altitude-angel-platform-launch-hailed-as-a-key-step-for-uk-aviation.
Legacy:
UTM Basic (notify):
UTM Ready (connected):
> Adding Legacy, UTM Basic and UTM Ready display

- Controls/PreFlight/CheckListControl.Designer.cs
- Controls/PreFlight/CheckListControl.cs
- MissionPlanner.csproj
Issue: In the PreFlight tab on the Data screen in Mission Planner, the Preflight group boxes do not change their size when resizing the panel.
Fix: The Preflight group boxes and their components will now resize according to the size of the panel. A Resize Event Handler has been added into the CheckListControl file, as well as a function to resize the desc label text to fit the text better onto the screen for checks containing longer strings.
> PreFlight tab: Resizing fix

- ExtLibs/Utilities/adsb.cs
Fix needed for custom plugin work. Fixes AVR and Beast binary input formats to see call sign and ground velocity in ADSB displays.
> ADSB: fix AVR and Beast modes to display call sign and velocity.

- mavcmd.xml
This is a minor fix so that the IMAGE_START_CAPTURE commands columns are filled in.
This has been lightly tested on my PC to confirm the command column headers appear
BTW, there's actually a fourth column, "Sequence Number", that we don't support so I've left that field out ([see command definition here](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1670))
> mavcmd: add image-start-capture command columns

- mavcmd.xml
A follow-up to PR https://github.com/ArduPilot/MissionPlanner/pull/3175 this adds the [image-stop-capture command](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1693) which will be added to AP shortly (see https://github.com/ArduPilot/ardupilot/pull/24772).
This has been lightly tested and looks good.
> mavcmd: add image-stop-capture command

- GCSViews/FlightData.cs
- temp.cs
Adds the target system id to the "safely switch" button.
Fixes issue when having multiple vehicles connected, pressing the "safety switch" button would not work.
> Temp: Add sysid target to safety switch command

- GCSViews/FlightPlanner.cs
- `processToScreen` redundantly converted units; the values in the datagrid cells should already be in display units
- `savewaypoints` did not convert back from display units before saving
While I was here, I added a commit to use consistent `ToString("0.00")` for the homealt text box.
> Pr bug homealt fileload

- GCSViews/ConfigurationView/ConfigRawParams.Designer.cs
- GCSViews/ConfigurationView/ConfigRawParams.cs
- GCSViews/ConfigurationView/ConfigRawParams.resx
This commit does 2 things:
1. Makes all columns but Desc and Fav manually sizeable (no more autosizing)
2. Stores and retrieves column widths from config.xml in absolute widths instead of percentages.
It actually makes more sense for most columns to remain a fixed size for various window sizes, and let the Desc column fill to take up any extra space. This PR solves multiple issues, from the autosize not working correctly cross-platform, to the tendency for the FAV column to accidentally getting larger and larger with each restart. Once the user has tuned the widths to taste, they never have to touch it again.
I also tweaked the default widths to what I think are sensible values.
> ConfigRawParams: manual absolute column sizing

- GCSViews/ConfigurationView/ConfigRawParams.cs
Currently the bitmask helper assumes int32, this means the sign bit in smaller masks cannot be set. `INS_HNTCH_HMNCS` is a example of a `int8` param. 
Currently the 8th bit will set the value to 128:
This is out of range for a int8, so when you write and read back you get a constrained down value of 127 which is a completely different bitmask. 
With this patch when setting the 8th bit:
We now get -128 which is the correct in range value for the int8 param type.
> GCSViews: ConfigRawParams: look up param type for bitmask helper

- GCSViews/FlightData.cs
This is a duplicate of my previous pull request: "FlightData - fixed QuickTab Color randomization #3151".
Issue experienced:
When loading extra QuickView items onto the QuickTab on the FLightData page of Mission Planner, the colours for the extra QuickTab Items added were all the same color.
Fix:
I have added in a list of additional colours for the QuickView Items to be coloured differently. The list contains 16 different colours and will be randomly chosen to be added to the next QuickView items added.
Removed white spaces changes from previous pull request.
> FlightData - Update to the Colour Randomization Quick Tab Numbers

- ExtLibs/Utilities/LogSort.cs
I'm not sure how well this works because I'm not able to get a VS environment set up.
The intent is to also sort log files based on BRD_SER_NUM. There are some uses for that parameter to identify what autopilot was used in which plane. Changes or other ideas are welcome. Maybe SYSID-SER_NUM format?
> LogSort: Add sorting by BRD_SER_NUM

- ExtLibs/Maps/WPOverlay.cs
I noticed to display DO_WINCH command as RALLY point of lat/lon=0,0.
I changed to equals because I feel that the greater is not necessary.
> WPOverlay: change the condition for rally point

- ExtLibs/Utilities/DFLog.cs
Commit #bb7d061 (BinaryLog: fix raw data extraction aka FILE)  broke messages display, it fixes it and keeps changes in the commit mentioned above.
> DFLog: Fix messages show as System.byte[]

- MainV2.cs
- NativeMethods.cs
Latest update in windows 11 breaks current implementation for hiding console window. 
This PR update the NativeMethods for using IntPtr and instead of find window, use GetConsoleWindow()
> MainV2: Fix console window hide in windows11

- ExtLibs/ArduPilot/CurrentState.cs
A partner recently asked for a 4th rangefinder on Discord. I decided to just go all the way to the ArduPilot limit like we do with batteries. Ten may be overkill, and I'm willing to pare that back if others object.
> CurrentState: add more rangefinders

- ExtLibs/Utilities/BinaryLog.cs
Correctly parsing the `System.Byte[]` to a string fixes the setting of the `_firmware` variable which is used to lookup the mode names from the numbers. Same idea as https://github.com/ArduPilot/MissionPlanner/pull/3210
Without we just get numbers:
With we get names again:
> ExtLibs: Utilities: BinaryLog: fix FW version detection used for mode names

- ExtLibs/ArduPilot/CurrentState.cs
There were an increased number of requests about using named floats to display data in the QuickView tab. Unfortunately, if the msg is sent with other than component ID 1, then it is displayed only when the component is selected in the connect window. (Sending it with compid 1 generates seqno errors so it is not recommended) This patch propagates named float messages across components with the same sysid. This will help in most cases. In the rare case when there is a need to separate named_floats by component id the propagation can be switched off by setting <propagateNamedFloats>false</propagateNamedFloats> in config.xml
> CurrentState: Propagate Named Float messages across components with same sysid.

- ExtLibs/Maps/WPOverlay.cs
Don't draw connecting lines from a VTOL_LAND to the next waypoint.
Before:
After:
> WPOverlay: treat VTOL_LAND like LAND

- ExtLibs/Utilities/BinaryLog.cs
Some byte arrays in logs are raw binary data, containing problematic characters (like newlines and other unprintables). Others are printable strings meant to be displayed. This allows both to be handled.
This fixes an issue Randy was having with "FILE" messages containing newlines, which was messing up a .log analysis he's working on.
> BinaryLog: escape characters in byte arrays

- GCSViews/ConfigurationView/ConfigHWOptFlow.Designer.cs
- GCSViews/ConfigurationView/ConfigHWOptFlow.cs
- GCSViews/ConfigurationView/ConfigHWOptFlow.resx
The Configuration -> Optional Hardware -> Optical Flow page hasn't worked in some time - ever since Ardupilot removed the ``FLOW_ENABLE`` parameter.
This PR updates the page to working with the new ``FLOW_TYPE`` parameter and other common optical flow parameters.
Tested on a copter and rover.
> GCSViews: Update optical flow config page

- ExtLibs/Maps/WPOverlay.cs
Loiter circles should draw at their individually-specified radii, if specified. Also, the exit tangent was hard-coded to assume counter-clockwise orbits.
Additionally, I made a minor correction to where the tangent point is drawn, so that it's truly tangent to the circle. Previously we were just adding/subtracting 90 degrees from the bearing.
> WPOverlay: fix loiter circle rendering

- ExtLibs/AltitudeAngelWings.Plugin/ControlOverlayMessageDisplay.cs
- ExtLibs/AltitudeAngelWings/ObservableProperty.cs
- ExtLibs/AltitudeAngelWings/Service/Messaging/IMessagesService.cs
- ExtLibs/AltitudeAngelWings/Service/Messaging/MessagesService.cs
On long flights the message display would progressively consume more CPU and memory, eventually making Mission Planner very slow. This PR fixes that problem. The cause was to do with the async calls trying to context switch between the same context and too many context. Instead, the context is now disconnected from the async calls so removing a message can happen in a different context from adding. In addition, the number of contexts being created has been reduced.
> Fixing a performance problem in message display

- MissionPlanner.csproj
Added apostrophes to allow run post-build command when the project parent folder contains spaces.
> MissionPlanner.csproj : Fix post build command to accept space in folder names

- ExtLibs/Utilities/DisplayView.cs
- GCSViews/ConfigurationView/ConfigSerial.Designer.cs
- GCSViews/ConfigurationView/ConfigSerial.cs
- GCSViews/ConfigurationView/ConfigSerial.resx
- GCSViews/InitialSetup.cs
- GCSViews/InitialSetup.resx
- MissionPlanner.csproj
- SerialOptionRules.json
Collects all information about serial ports on a single screen. Using rules defined in the SerialOptionRules.json to add comments and set mandatory options/baudrate when a certain protocol selected.
> Setup: SerialPort settings screen

- ExtLibs/Utilities/adsb.cs
tl;dr: add ground track, speed, callsign, squawk codes, fix math error causing altitude discrepancy.
While writing https://github.com/MUSTARDTIGERFPV/MavADSB I discovered a few quirks about the ADS-B SBS-1 processing in Mission Planner. This PR addresses those quirks.
1. Ground track, speed, callsign, are parsed in SBS-1 message types one and four, but UpdatePlanePosition is called only in type 3. Its ground speed was fixed to -1, and the callsign wasn't set at all. This changes that behavior so all fields get updated as soon as a type 3 is seen using the values stored from the type 1 and type 4 messages.
2. Squawk codes were not interpreted at all - they've been added.
3. Previously, the altitude value sent OTA was divided by a factor which represents the number of meters in 10ft. Given …
> Improve/Fix SBS-1 ADS-B Parsing

- ExtLibs/AltitudeAngelWings/Service/AltitudeAngelService.cs
In rare cares where map data returns multipolygons it could cause an ArgumentException to be thrown as the overlay feature IDs for each polygon in the multipolygon would match. This fix avoids this.
> Minor bug fix for multipolygons in map

- mavcmd.xml
This slightly changes what the Plan page shows in the command list for DO_CHANGE_SPEED for Copters by adding the available options 0, 2 and 3.  I think many users do not know about 2 and 3.
Below are before vs after shots of what the Type field looks like.  In the 2nd "AFTER" it shows what is displayed when the user hovers over the field.
> mavcmd: do-change-speed Type field includes possible values

- GCSViews/FlightData.cs
a user tried to toggle safety on an antenna tracker and MissionPlanner sent it to target_system=0, which resulted in toggling safety on a flying aircraft, causing it to crash
Note that we really should make it a separate on/off buttons, as per this issue: https://github.com/ArduPilot/MissionPlanner/issues/3268
This is what MissionPlanner sent:
```
2023-09-16 08:52:05.284 SET_MODE {target_system : 0, base_mode : 128, custom_mode : 1}
2023-09-16 08:52:05.308 SET_MODE {target_system : 0, base_mode : 128, custom_mode : 1}
```
I can only guess that MissionPlanner had not seen a SYS_STATUS from the antenna tracker when the button was pressed
> prevent target_system=0 in toggle safety switch

- ExtLibs/ArduPilot/CurrentState.cs
CurrentState.climbrate will use VFR_HUD.climbrate if we receive the message. Otherwise, it falls back to the time/altitude change calculation.
This will fix: #3245
> CurrenState :Use VFR_HUD for climbrate IF it is received.

- ExtLibs/GMap.NET.WindowsForms/GMap.NET.WindowsForms/GMapControl.cs
- ExtLibs/Maps/GMapMarkerQuad.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/FlightData.cs
When rotate map with plane checked, the vehicle overlays was not displayed.
Also add a cross check to disable showing nofly zones when rotating map, (and vica versa) since rotating and displaying nofly overlay is very time consuming and grinds the UI to halt.
This fixes #3191
> FlighData: Fix rotated map not displaying vehicle

- Common.cs
- ExtLibs/ArduPilot/CurrentState.cs
- Swarm/Formation.cs
This fixes the turn radius display on the map when using other speed units
> CurrentState: correct unit handling for `radius`

- ExtLibs/ArduPilot/CurrentState.cs
This PR updates the gimbal attitude with the GIMBAL_DEVICE_ATTITUDE_STATUS MAVLink message, alongside the existing MOUNT_STATUS message.
AP uses the GIMBAL_DEVICE_ATTITUDE_STATUS message instead of the older ardupilot specific MOUNT_STATUS message by [this](https://github.com/ArduPilot/ardupilot/pull/21243).
> CurrentState: handle GIMBAL_DEVICE_ATTITUDE_STATUS message

- GCSViews/FlightData.cs
Makes QuickView add window fixed size, based on the Main window size (smaller by 50 pixel on each side) and make it fixed scrollable. This solves the issue with small screens where the bottom lines are inaccessible.
> Make QuickView Add window fixed size and scrollable.

- SerialOptionRules.json
Remove rules for set tx/rx inversion on RCIN, since it is done automatically.
> ConfigSerial: Update SerialOptionRules.json

- ExtLibs/Utilities/DisplayView.cs
- GCSViews/SoftwareConfig.cs
- MainV2.cs
Disable Standard and Advanced Param view and enables FullParamList in basic and advanced views.
custom layouts not impacted, if needed Advanced and Standard param pages can be enabled.
This fixes #3270
> DisplayView: Disable ConfigStandardParams and ConfigAdvancedParams 

- ExtLibs/ArduPilot/Joystick/JoystickBase.cs
- Joystick/JoystickSetup.cs
This fixes the issue where the Expo values for the Joystick configuration were not being saved correctly.
> Joystick: fix expo saving function

- GCSViews/ConfigurationView/ConfigRawParams.cs
If a param change causing the change in the number of parameters, the parameter subsystem could stuck in a "downloading is in progress" state. This pr:
removes the name check, since not only _enable parameters can change the number of parameters
Add a check at the end of Write Params and if the reported param number not equals with the current number, it notify the user and do a param refresh.
This fixes #3198
> ConfigRawParams: When setting a parameter changes the number of parameters, do a full refresh. and check if reboot is needed

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
Sometimes a statustext sneaks through before the version comes in. ArduPilot 3.4 came out in 2015, so I think we can safely remove this now. I could do something backward-compatible instead if we want, but it would be messy.
> MAVLinkInterface: remove legacy text severity

- ExtLibs/Utilities/Device.cs
> ExtLibs: add new device ids to list

- mavcmd.xml
This adds the new SET_CAMERA_SOURCE mission command to the list of possible commands for copter, rover and plane.
This change requires this mavlink PR https://github.com/ArduPilot/mavlink/pull/351 to be merged which should happen at tomorrow's dev call (e.g. Mar 19th).
This has been lightly tested and seems OK to me.
The only issue is that we get an invalid number error because the mavlink change hasn't gone in yet.
> mavcmd: add set-camera-source

- GCSViews/ConfigurationView/ConfigDroneCAN.cs
Now we have MAVCAN slcan is not required, this allows the config page to still be used, only the SLCAN button is disabled. 
This allows me to use the page in SITL where the is no `CAN_SLCAN_TIMOUT`.
> GCSViews: Config DroneCAN allow with no SLCAN port

- Grid/GridUI.Designer.cs
This is a straightforward change: we work with high-altitude balloons intending to do aerial photogrammetry. We need to set flight altitudes of 15km to 35km.
I've tried out the solution and the calculations using this higher altitude seem to be correct.
> Grid: max altitude increased to 99999m to allow HAPS to use the calculation

- ExtLibs/Utilities/Device.cs
added SCHA63T to imu types in Device.cs.
https://github.com/ArduPilot/ardupilot/pull/26871
> ExtLibs: add SCHA63T to imu types of device ids

- ExtLibs/Utilities/srtm.cs
our SRTM1 and SRTM3 now cover whole world
terrain.ardupilot.org SRTM1 has covered the whole world since 2022
SRTM3 covers whole world from April 2024
> srtm: removed 60N limit on SRTM downloads

- .github/workflows/android.yml
- Common.cs
- ExtLibs/Maps/GMapMarkerBase.cs
- ExtLibs/Maps/GMapMarkerBoat.cs
- ExtLibs/Maps/GMapMarkerHeli.cs
- ExtLibs/Maps/GMapMarkerPlane.cs
- ExtLibs/Maps/GMapMarkerQuad.cs
- ExtLibs/Maps/GMapMarkerRover.cs
- ExtLibs/Maps/GMapMarkerSingle.cs
- ExtLibs/Maps/GMapMarkerSub.cs
- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.ko-KR.resx
- GCSViews/ConfigurationView/ConfigPlanner.pt.resx
- GCSViews/ConfigurationView/ConfigPlanner.resx
- GCSViews/ConfigurationView/ConfigPlanner.ru-KZ.resx
- GCSViews/ConfigurationView/ConfigPlanner.uk.resx
- GCSViews/FlightData.cs
- MainV2.cs
This allows the user to select whether other MAVs, or other instances of the same MAV on redundant links, should be hidden from the map, or displayed as transparent to be less distracting, or displayed as normal. The setting defaults to normal.
Additionally, added settings on the Config > Planner page to allow control over settings that were previously only available with config hacking.
Shown below is the image of one aircraft coming in over three redundant links (Radio, LTE, and SatCom) using the `Transparent` display option.
Screenshot of new config options
I had to do some funny naming nonsense for the Quad map marker. This was done keeping two things in mind:
1) Avoid constructing pens and brushes over and over assuming there is some performance penalty for that.
2) Avoid breaking …
> GMapMarkerBase: add options for transparent MAVs

- ExtLibs/Utilities/Septentrio.cs
- GCSViews/ConfigurationView/ConfigSerialInjectGPS.Designer.cs
- GCSViews/ConfigurationView/ConfigSerialInjectGPS.cs
- GCSViews/ConfigurationView/ConfigSerialInjectGPS.resx
- MainV2.cs
This adds a checkbox to enable automatic base station setup for Septentrio receivers.
> gps base: add automatic base station configuration for Septentrio

- GCSViews/FlightPlanner.cs
If user creates the Takeoff mission item by placing down a waypoint and the change it to Takeoff the coordinates will remain and it lead to a false route drawing.
> FlighPlanner: When a WP changed to Takeoff zero out Lat,Lng

- GCSViews/FlightPlanner.cs
If the vehicle does not have a Home Location yet and user click on the Home Location link to the right side, zoomToHome moves to the map to 0,0. Now it check if there is a valid Home Location or Planned Home location and use that .
> FlighPlanner: Fix map moving to 0,0 when HomeLocation clicked 

- ExtLibs/Utilities/Settings.cs
Fixes when RemoveList tries to remoce the last item in a list. It calls SetList, but it returns without setting the key if the list is empty. So the last item is not cleared from a list.
> Settings:Fix RemoveList to remove last item in the setting

- GCSViews/ConfigurationView/ConfigInitialParams.cs
The lower accel filter value is what we’ve been using for quite some time now due to Leonard Halls recommendation, and the initial parameters is the best way to get this into new builds without changing the default value or affecting upgrades of existing copters. Any other method will put extra work load on Randy.
The slightly different thrust expo calculation is derived from collected data and some experimentation. The biggest change is very large prop sizes will be limited to around 0.80 thrust expo instead of going unrealistically high. This does also give slightly lower thrust expo values for smaller props, but still fits with flight data.
> ConigInitialParams: Mot thrst calc changes as requested by Xfacta

- ExtLibs/ArduPilot/CurrentState.cs
the ESCs on the status page only go up to 12, but in 4.5 we support at least 16
> CurrentState: Add ESC13-16 telemetry

- GCSViews/FlightData.cs
Some languages (Turkish for example) converts small case i to a special character. Which breaks commands like Preflight_Calibration
> FlightData.cs : Cultureinfo to ToUpper on commands

- Controls/RelayOptions.cs
- GCSViews/FlightData.resx
As asked in #3380  Relays display name starts from 1 instead of zero
Change the flow of controls in servoTab for a tidier look.
> FlighData : Relay display name start from 1

- ExtLibs/ArduPilot/CurrentState.cs
As per mavlink, rcin.rssi is 0-254, 0 being the worst and 254 being the best and 255 invalid/unknown
Fixes #3371
> CurrentState: fix rxrssi scaling and when rcin.rssi is 255 (invalid/unknown)

- GCSViews/FlightPlanner.Designer.cs
- GCSViews/FlightPlanner.cs
- GCSViews/FlightPlanner.resx
Add progress bar
Add summary of tiles injection per zoom
Load the Custom map and reload the map after injection
> FlightPlanner : Inject Custom Map tiles and reload map into custom

- ExtLibs/Mavlink/MAVLinkParam.cs
Rounding to a fixed number of decimal places leads to over rounding small numbers and under-rounding big numbers. I first encountered this problem when dealing parameter values in the range of 10^-6 that kept getting way rounded off. That's not a common order of magnitude for a parameter in ArduPilot, but we shouldn't rule it out (in my case, they were part of a lua script; I don't think any official params are in this range).
Some samples from the "Immediate Window" in Visual Studio
```
(double)0.8f
0.800000011920929
Math.Round((double)0.8f, 7)
0.8
RoundToSignificantDigits((double)0.8f, 7)
0.8
(double)100.8f
100.80000305175781
Math.Round((double)100.8f, 7)
100.8000031
RoundToSignificantDigits((double)100.8f, 7)
100.8
(double)8e-9f
7.9999997737445483E-09
Math.Round((double)8e-9f, 7)
0 …
```
> MAVLinkParam: fix rounding to 7 digits

- ExtLibs/GMap.NET.Core/GMap.NET/GMaps.cs
- ExtLibs/GMap.NET.Core/GMap.NET/PureImageCache.cs
- ExtLibs/GMap.NET.WindowsForms/GMap.NET.WindowsForms/TilePrefetcher.cs
- ExtLibs/Maps/MyImageCache.cs
- GCSViews/FlightPlanner.cs
When prefetching, do not download tile if file already exist
Add minZoom input in prefetch (like maxZoom)
Use Parallel.For instead of For to get tiles faster !
Using original for loop to download world from zoom 5 to 1 :
Middle of land at zoom 12 to 10 :
Using Parallel.For loop to download world from zoom 5 to 1 :
Middle of land at zoom 12 to 10 :
> FlightPlanner : tweak prefetch, Resolves #2591, resolves #2483

- temp.cs
Toggle safety switch should perform the same in both action tab and ctl-F screen.
Cloned from FlightData.cs
#3176 
#3269
> Also check target_system!=0 when toggling safety switch in ctl-F screen.

- ExtLibs/ArduPilot/CurrentState.cs
Some speech events, like mode changes, fire off on all connected com ports, not just the primary. Additionally, `CurrentState` ignores the `speechenable` flag of the `MAVLinkInterface` that it's attached to, causing it to go off even for interfaces that are supposed to be silent.
This PR makes `CurrentState` honor the `speechenable` flag. Additionally, it sets `speechenable` on an interface when `MainV2.comPort` is set to that interface, and clears `speechenable` on the old interface that `MainV2.comPort` was pointing to.
> CurrentState: honor MAVLinkInterface.speechenable

- Controls/MyDataGridView.cs
- GCSViews/ConfigurationView/ConfigRawParams.cs
1) Add double buffering to MyDataGridView. Prevents dangerous graphical corruption that can occur when scrolling, causing the name of the parameter you are editing to look like a different parameter. See this example; the `CAN_P1_BITRATE` parameter is falsely labeled as `CAN_LOGLEVEL`:
2) Fix an off-by-one error on a row-check that broke additional controls, like the bitmask button, on row 1
3) Stop the tree view from taking favorites into account:
> ConfigRawParams: Various bugfixes

- Controls/ConnectionOptions.cs
- Program.cs
When launching redundant links with `ConnectionOptions`, it would always use the old-school param download, and the theme of the progress window would be wrong.
> ConnectionOptions fixes

- Msi/installer.bat
From 1.3.82 wix.exe is generated in the net472 subfolder instead in the msi folder...
> MSI: Update installer.bat

- ExtLibs/Utilities/srtm.cs
- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.resx
- Program.cs
- Add ComboBox in ConfigPlanner to choose if map is loaded from cache only, server only or cache and server (default). This setting is saved in the config.xml
- Add button in ConfigPlanner to Open Map Cache Folder
- SRTM files are downloaded if GMaps Access Mode is not CacheOnly
This greatly reduces cpu load and unnecessary network access in case of using an offline GCS.
I don't know if i need to modify all ConfigPlanner.resx file's language as well ?
> Config Planner - Choose how to access the map tiles : server, cache or both

- MissionPlanner.sln
- Plugins/TerrainMakerPlugin/Location.cs
- Plugins/TerrainMakerPlugin/TerrainDataFile.cs
- Plugins/TerrainMakerPlugin/TerrainMakerPlugin.cs
- Plugins/TerrainMakerPlugin/TerrainMakerPlugin.csproj
You can create TERRAIN DAT files to copy to the FC's SD card from the terrain database available in Mission Planner
!Including loaded DEM files!
The resolution can be selected between 5 and 100 meters, if the available terrain data is lower resolution then the grid data will be averaged.
(less than 5 meter resolution is not possible due to a bug in Ardupilot, which prevents files larger than 2Gb on SD cards)
Use :
Go to FlightPlanner.
Select area with ALT+MouseCLICK and drag
Open context menu and select Make Terrain DAT
if no area is selected the actual displayed area is used.
Note: DAT files are always created for one by one degree area, the size depends on the resolution.
> Plugin: Create Terrain DAT file for uploading

- GCSViews/ConfigurationView/ConfigDroneCAN.cs
Adds a disconnect so you can switch from bus 1 to bus 2 easily.
> ConfigDroneCAN: Add disconnect button

- Controls/paramcompare.cs
Fixes bug reported by Alex/ARACE on Discord:
There might be a more efficient way to do a double compare that accounts for epsilon differences, but this works.
> paramcompare: remove double inequality check

- GCSViews/ConfigurationView/ConfigSerialInjectGPS.cs
Fix Septentrio config error while connected to ublox and changing away from the config RTK/GPS screen.
if "SerialInjectGPS_SeptentrioRTCMLevel" is not set, then the combo box is set to 1, which triggers the update....
> ConfigSerialInjectGPS.cs: Fix Septentrio config error while connected to ublox and changing away from the config RTK/GPS screen.

- GCSViews/FlightData.cs
This PR contains updates to the interface with the ping200X in the Transponder tab. Co-requisite with the ArduPilot PR https://github.com/ArduPilot/ardupilot/pull/28419
Changes:
- Fix a display error where the "ON" button was not properly bolded when the transponder mode was set to "ON"
- It should be bold when the status message indicates mode A, S, and 1090ES are on and mode C is off
- Requests the UAVIONIX_OUT_STATUS mavlink message at 1 Hz when it first gets that same message
- This enables smarter timeout behavior; see next point
- Make controls/display more responsive to connection errors with the transponder
- Display "Transponder Offline" when status message is received but the flag `UAVIONIX_ADSB_OUT_STATUS_FAULT_STATUS_MESSAGE_UNAVAIL` is set.
- Display "Transponder Status Lost" …
> ADSB: uAvionix Transponder Updates

- GCSViews/FlightData.Designer.cs
This is my first Mission Planner pull request so please let me know if I have missed something. 
We have an ArduPilot Partner request that we increase the maximum limit (currently at 1000), of this button:
I have increased it by an arbitrary number.
> Increase "Change Alt Button" maximum

- GCSViews/InitialSetup.cs
- GCSViews/SoftwareConfig.cs
It makes possible for a plugin to add pages to the SETUP and the CONFIG pages.
Simply create a MyUserControl based form and then add it via
` SoftwareConfig.AddPluginViewPage(typeof(pageclass), "pagename");`
or 
` InitialSetup.AddPluginViewPage(typeof(pageclass, "pagename");`
> Add interface for plugins to add HW and SW config pages

- MissionPlanner.csproj
- Plugins/example22-payloadconfig.cs
Adds an example for the new plugin config/setup page interface: #3433.
This example implements a payload selection page to reconfigure parameters based on what payload you have installed:
By default, this plugin doesn't load. Someone has to add payloads to the .cs file first.
If we like this, I'll write up a post about it on Discuss.
> Example22: Payload Select Config Page

- GCSViews/FlightPlanner.cs
Apparently Google Earth Pro produces malformed KMLs by skipping default values at least for colors and line widths.
And it caused KML overlay load fail.
Fixes Issue : https://github.com/ArduPilot/MissionPlanner/issues/3443
> KML overlay: Fix missing default color or width linestyle errors

- ExtLibs/Utilities/Warnings/CustomWarning.cs
- MainV2.cs
The RepeatTime setting was also the worst-case detection time
As implemented, no matter what, the condition is checked every `RepeatTime` seconds. At the default time of 10, this means it could take up to 10s before the warning manager tells you that something bad happened. On average it takes 5.
This fixes it so the last repeat time only gets recorded when the check returns true. So, after this function returns true, it will not check again for another `RepeatTime` seconds.
Also a driveby fix of the initialization of the `_speech` member of the warning engine. It was always initializing to null due to being initialized before the user's speech settings were loaded.
> Fix Warning Repeat Time

- GCSViews/FlightData.cs
This [commit](https://github.com/ArduPilot/MissionPlanner/commit/eefd2167358c5c121c61b58f0eab4f85034d5ef8#diff-14ff4d1be768ca629959b5d1f5efdb8058bd7b9c448b74681ef87c509eac4c89R4074) by @MUSTARDTIGERFPV changed the squawk text to be shown in Hex. I'm not sure why, maybe he knows? I've never seen it expressed as a decimal. Technically it's an octal number but decimal is the normal conversion.
> Fix ADSB Squawk back to decimal

- GCSViews/FlightData.cs
Reverts ArduPilot/MissionPlanner#3452
See https://github.com/ArduPilot/MissionPlanner/pull/3452#issuecomment-2499089874 for rationale; a 4-digit hex representation is the aviation-standard way to display octal squawk codes.
> Revert "Fix ADSB Squawk back to decimal"

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
- GCSViews/FlightData.cs
Allows IC Engines to be used without an RC switch.
> FlightData: Actions: add engine start/stop

- ExtLibs/ArduPilot/CurrentState.cs
This PR allows you to set GCS_PID_MASK to 7 and display SRate for roll/pitch/yaw simultanously. During tuning last week, I wanted to be able to display SRate for roll and pitch simultaneously while I adjusted some filters and gains in flight.
I could expand this to track every PID variable per axis, but it would be messy, and this is all I need immediately.
> CurrentState: add individual SRate variables

- ExtLibs/Utilities/Download.cs
Files that took more than 30s to download were failing.
This change makes GetAsync/SendAsync return the response as soon as the header comes in, which makes the progress bar/ETA work as intended. Previously, the entire file would be downloaded before the response could even be checked, causing timeouts for large files or slow connections.
I can't get GStreamer to install itself at my appartment without this.
> Download: fix getFilefromNet for slow downloads

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
If `CONNECT_TIMEOUT_SECONDS` greater than 60 seconds remain seconds calculated in wrong way. And we can get maximum 60 seconds timeout.
> Fix MavLink Connection Timeout

- ExtLibs/Xamarin/Xamarin/Resources/mavcmd.xml
- GCSViews/FlightPlanner.cs
- mavcmd.xml
This fixes an issue where commands that used the <Z> parameter for anything other than altitude were getting unit conversions applied when they shouldn't have been. I'm also adding a unit label to the altitude column.
This also opens up the possibility of converting units (distance or altitude) for other columns, which I'll do next, probably as part of this PR, but I haven't gotten that far yet.
This will take some careful review to make sure I haven't screwed things up. I looked long and hard at all the places in FlightData that look at `multiplieralt`, but I could have missed something. I've done some basic testing, and it appears to be working.
One thing I noticed is that we don't seem to updata `mavcmd.xml` when we update Planner. If the file exists, we don't overwrite it with the one …
> Add unitType attribute to mavcmd.xml

- ExtLibs/Comms/CommsSerialPort.cs
- GCSViews/ConfigurationView/ConfigPlanner.Designer.cs
- GCSViews/ConfigurationView/ConfigPlanner.cs
- GCSViews/ConfigurationView/ConfigPlanner.resx
- MainV2.cs
For some weird reason the WinSerial driver coupled with the ESP32 SerialOverUSB drive changes the RTS line at connect. But only at the first connect after power up.
The fix is to set RTS/CTS handshake enable but just for the open command, and disable it immediately.
I added a new option to Planner Settings to enable this function, so it can be enabled only on when needed, and does not interfere with any other serial settings.
Note: If you once had a reset on connect, it stuck so you have to remove/reconnect the esp32 before trying again.
> Fix ESP32-C3 Dronebridge Reset on First connect on Windows

- ExtLibs/Xamarin/Xamarin/Resources/mavcmd.xml
- mavcmd.xml
Command/mission item implemented but not listed
> MissionPlanner:add DO_SET_HOME to Copter and Rover

- Utilities/ExtensionsMP.cs
When minimizing a form generated by ShowUserControl, the client size gets set to 0, which causes issues when the form is restored. The easiest place to see this is the Joystick config window, but that has a minimum size; it's much worse on things that don't have a minimum size, like the bitmask parameter popup.
Sizes should only be copied when the window state is normal.
> ExternsionsMP: fix ShowUserControl minimize bug

- GCSViews/FlightData.cs
This addition of `saveTabControlActions` here means that users cannot save their visibility preferences for the plugin-added tabs. Plugin tabs don't exist when this first gets called, so their visibility settings get wiped out on startup. 
Currently, plugins have to do one of the following:
1. Force the tab on every time, making the user disable the plugin to hide the tab
2. Force the user to unhide the tab every time
3. Make a redundant setting to watch the `tabcontrolactions` setting and save a backup of the user's preference to restore later.
Removing this line should have no negative impacts.
> FlightData: allow plugin tab visibility to persist

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
Very minor nitpick I noticed when I was testing #3483. This was putting the newline in the wrong spot in the console.
> MAVLinkInterface: tidy plaintxtline printing

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
treating 'U' as a header marker byte leads to the problem that we will accidentally consume parts of a valid packet after receiving a "plain text" message.
This is particularly problematic in ArduPilot's config-error-loop, as we emit the problem as both statustext and raw "line noise" to the GCS; the statustext is lost, mneaning the user doesn't get any specific error message from the autopilot, just "in config error loop".
> MAVLinkInterface.cs: remove 0.9 from mavlink parser

- ExtLibs/Controls/ControlHelpers.cs
- GCSViews/FlightData.cs
There is a bug where a user can be persistently stuck with a full-screen sized, or a zero sized, EKF status window (or Vibe or PreArm messages windows). We don't allow the user to resize these windows, so the only way to fix it is with config.xml hacking (or deleting).
We hide the minimize/maximize buttons on these windows, but they can still be minimized or maximized in multiple ways: keyboard shortcut, double-clicking the titlebar, or from the context menu on the title bar. If the user does this, and then closes the window before restoring it, the size gets saved and it cannot be fixed through the UI.
This PR fixes this by saving the location and size of the `RestoreBounds` of the form, instead of the literal size.
Additionally I made the EKF/Vibe/PreArm windows always open in normal …
> Fix popout StartupLocation bug

- Controls/GimbalControlSettingsForm.cs
- Utilities/ThemeManager.cs
Michael brought this up during #3386, but I didn't get around to fixing it.
Now, any future classes that inherit `MyButton` will be automatically handled as `MyButton` by the theme manager.
> ThemeManager: auto theme child classes of MyButton

- ExtLibs/ArduPilot/CurrentState.cs
Some of the unit conversations for the HIGH_LATENCY2 message were incorrect, according to https://mavlink.io/en/messages/common.html#HIGH_LATENCY2
> Correct HIGH_LATENCY2 message units

- Controls/ConnectionStats.cs
- Log/LogDownloadMavLink.cs
- Log/LogDownloadscp.cs
The size of each log files is in bytes and it's not readable by humain (at least not by me). 
So i convert the size into Kb, Mb, etc... i use an already existing function ToHumanReadableByteCount at MissionPlanner.Controls.ConnectionStats and made it public to acess it.
Also add more information during downloading a file.
I also made  the (almost) same modifications for LogDownloadscp but i'm not able to test it. Maybe someone can ?
> LogDownloadMavLink : More readable info of files size and during downloding a file

- mavcmd.xml
This adds [DO_SET_ROI_LOCATION](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI_LOCATION) and [DO_SET_ROI_NONE](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI_NONE) to the list of available mission commands for Copter, Rover and Plane.
This has been lightly tested in SITL and seems fine except that the red marker does not appear on the map like it does for the older DO_SET_ROI command.  Maybe @EosBandi, @robertlong13 or @meee1 could tell me where I could update to fix this?  I suspect there's just some case statement that's missing an entry for DO_SET_ROI_LOCATION.
The corresponding AP flight code PR is here https://github.com/ArduPilot/ardupilot/pull/29567
> mavcmd: add do-set-roi-location and do-set-roi-none

- Common.cs
In 1.3.82, “Change icon Description” is no longer available for ArduCopter.
I believe it was removed by mistake and will be restored.
https://github.com/ArduPilot/MissionPlanner/commit/b6e8270a5a4307057d4f1d976f200a2685d42b1e
> Common: add mapicondesc for ArduCopter

- APMotorLayout.json
- GCSViews/ConfigurationView/ConfigMotorTest.cs
Support additional motor test information for tri frames. Goes along with [this ArduPilot PR](https://github.com/ArduPilot/ardupilot/pull/25670), and should probably not be merged until that one is.
This brings the motor test order in line with other frames. Starts with the front-right and works around clockwise, with the addition that "Motor C" controls the tilt servo, which is a little odd, but it's exactly what "Test all in sequence" does, so we should match that.
> ConfigMotorTest: support Tri frames

- ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
`setGuidedModeWP` can cause a double-setting of `giveComport` (due to it calling `setWP` for Plane). It should not need to set `giveComport` at all.
Typically, this just causes log spam, but for some reason, if a plugin calls it, it actually locks up the UI for several seconds when it hits `Debugger.Break()`.
> MAVLinkInterface: plane guided error

- GCSViews/FlightPlanner.cs
Realted issue: #3542 
Fixes resetting Altmode combobox to `Relative` mode after loading saved plan instead of loading last entry value.
> Fix AltMode resetting when loading saved Flight plan

- Controls/DevopsUI.cs
- ExtLibs/Comms/CommsNTRIP.cs
- ExtLibs/Strings/Strings.Designer.cs
- ExtLibs/Strings/Strings.az-Latn-AZ.resx
- ExtLibs/Strings/Strings.id-ID.resx
- ExtLibs/Strings/Strings.ja-JP.resx
- ExtLibs/Strings/Strings.ko-KR.resx
- ExtLibs/Strings/Strings.pt.resx
- ExtLibs/Strings/Strings.resx
- ExtLibs/Strings/Strings.ru-KZ.resx
- ExtLibs/Strings/Strings.tr.resx
- ExtLibs/Strings/Strings.uk.resx
- ExtLibs/Strings/Strings.zh-Hans.resx
- GCSViews/ConfigurationView/ConfigAntennaTracker.cs
- GCSViews/FlightData.cs
New behavior: 
This seems to be a common misspelling in the repo. I propose fixing it in user-facing strings. 
https://word.tips/spelling/response-vs-responce/
> Fix response spelling in user-facing messages

- ExtLibs/ArduPilot/CurrentState.cs
The mavlink efi status message uses units of cm3/min, not g/min as displayed currently in MP
> Update efi fuel flow units

- GCSViews/FlightPlanner.cs
Updates the takeoff altitude prompt to display the current altitude unit.
The default takeoff altitude is adjusted based on selected unit.
Will Skip the Pitch prompt for Quadplanes if Q_OPTIONS bit 1 is disabled
Relies on reading params so does rely on connection to a quadplane to skip pitch
May need to add a setting in planner at some point to have a default firmware type when disconnected from an aircraft.
> FlightPlanner: Add units to Takeoff prompt & skip pitch for VTOL

- Plugins/OpenDroneID2/OpenDroneID_UI.cs
if the operator GPS becomes unplugged we should tell the flight controller that we no longer have a position, so pre-arms can fail correctly
> ODID: send 0/0 operator location

- ExtLibs/uno/UnoUI/UnoUI.Shared/test/MissionPlanner.temp.xaml
- temp.resx
Corrected some typos which I observed while using the Advanced Tools UI (temp UI) within Mission Planner, which is accessed via the CTRL+F shortcut.
> temp.resx: Correct typos in button texts and related descriptions shown on the Advanced Tools UI

- ExtLibs/Controls/HUD.cs
When addind text with color different from red, it's not centered in the HUD :
Now with the color to calculate the size, the text is centerd in the HUD :
> Fix color and position of text messages in HUD
