mavcmd.xml
Done regarding to issue https://github.com/ArduPilot/ardupilot/issues/3753
=> Flexible waypoint type #3753

GCSViews/ConfigurationView/ConfigPlanner.ar.resx, GCSViews/ConfigurationView/ConfigPlanner.id-ID.resx, GCSViews/ConfigurationView/ConfigPlanner.ja-JP.resx, GCSViews/ConfigurationView/ConfigPlanner.ko-KR.resx
fix the text in other language
=> ConfigPlanner: change the text value from Vario to Layout

CurrentState.cs, ExtLibs/Controls/HUD.cs, GCSViews/FlightData.Designer.cs
Preliminary PR for AOA and SSA estimation receive and display testing.
Depends on merging of:
https://github.com/ArduPilot/mavlink/pull/32
https://github.com/ArduPilot/ardupilot/pull/5933
=> AOA and SSA receive, AOA indication, bulls eye indication

Utilities/BoardDetect.cs, Utilities/Firmware.cs, temp.cs
This pull request adds Pixhawk 3 Pro support to Mission Planner. The corresponding firmware is available in a stable branch for ArduPlane, ArduCopter and ArduRover at the moment. Another PR has been submitted in order to update the XML firmware file : https://github.com/ArduPilot/binary/pull/9
=> Add px4fmu-v4pro support

GCSViews/ConfigurationView/ConfigArdurover.Designer.cs, GCSViews/ConfigurationView/ConfigArdurover.cs, GCSViews/ConfigurationView/ConfigArdurover.resx
This adds some of the for Rover 3.2. 
I am not sure how to add the combo boxes with the text selection.
See https://github.com/ArduPilot/MissionPlanner/issues/1691
=> ConfigArdurover: Add tuning options for 3.2

ExtLibs/Utilities/DisplayView.cs, MainV2.cs
Added the ability to create custom layouts where the menu is always hidden by default to save on screen space. The ability to toggle the autohide feature is also hidden from layouts with this feature turned on.
This feature has not been applied to any of the included layouts.
=> Added the ability to create layouts with menu autohide always turned on.

ExtLibs/px4uploader/Uploader.cs, Utilities/BoardDetect.cs
BoardDetect: detect board_type 33 as fmuv3
Uploader: allow board_type 33 to load fmuv3 firmware
=> Add AUAV/mRo X2.1 support to MissionPlanner

camerasBuiltin.xml
We would like to provide the parameters of our camera to our clients that will eventually use Mission Planner.
Thank you in advance,
AeroHawk Technologies
=> Adding the AeroHawk camera parameters to the camerasBuiltin.xml file

GCSViews/ConfigurationView/ConfigESCCalibration.resx
Minor Spelling fix:
ESCs should beep as the are calibrated
-to-
ESCs should beep as theY are calibrated
=> Minor Spelling fix

GCSViews/ConfigurationView/ConfigFailSafe.ja-JP.resx, GCSViews/ConfigurationView/ConfigFirmware.ja-JP.resx, GCSViews/ConfigurationView/ConfigFirmwareDisabled.ja-JP.resx, GCSViews/ConfigurationView/ConfigFrameClassType.ja-JP.resx, GCSViews/ConfigurationView/ConfigFriendlyParams.ja-JP.resx, GCSViews/ConfigurationView/ConfigHWAirspeed.ja-JP.resx, GCSViews/ConfigurationView/ConfigHWCompass.ja-JP.resx, GCSViews/ConfigurationView/ConfigHWOSD.ja-JP.resx, GCSViews/ConfigurationView/ConfigHWOptFlow.ja-JP.resx, GCSViews/ConfigurationView/ConfigMandatory.ja-JP.resx, GCSViews/ConfigurationView/ConfigMotorTest.ja-JP.resx, GCSViews/ConfigurationView/ConfigOptional.ja-JP.resx, GCSViews/ConfigurationView/ConfigPlanner.ja-JP.resx, GCSViews/ConfigurationView/ConfigSimplePids.ja-JP.resx, GCSViews/FlightData.ja-JP.resx, GCSViews/Help.ja-JP.resx
I'm ArduPilot user in Japan.
I found some strange Japanese. So I'll fix it step by step.
=> Fixed a bit strange part of Japanese display.

GCSViews/ConfigurationView/ConfigFirmware.ja-JP.resx, GCSViews/FlightData.ja-JP.resx, GCSViews/FlightPlanner.ja-JP.resx, ScriptConsole.ja-JP.resx
Fix some Japanese for Firmware install, FlightData, FlightPlanner, ScriptConsle.
=> Improvement japanese

GCSViews/ConfigurationView/ConfigAntennaTracker.ja-JP.resx, GCSViews/ConfigurationView/ConfigArducopter.ja-JP.resx, GCSViews/ConfigurationView/ConfigArduplane.ja-JP.resx, GCSViews/ConfigurationView/ConfigArdurover.ja-JP.resx, GCSViews/ConfigurationView/ConfigFriendlyParams.ja-JP.resx, GCSViews/ConfigurationView/ConfigPlanner.ja-JP.resx, GCSViews/ConfigurationView/ConfigRawParams.ja-JP.resx, GCSViews/ConfigurationView/ConfigRawParamsTree.ja-JP.resx, GCSViews/Help.ja-JP.resx, GCSViews/InitialSetup.ja-JP.resx
This is the last pull request for next release for Japanese improvement.
=> Japanese improvement

GCSViews/ConfigurationView/ConfigBatteryMonitoring.cs, GCSViews/ConfigurationView/ConfigFailSafe.cs, Wizard/_7BatteryMonitor.cs
=> update power module and battery failsafe config

Strings.resx
Per https://discuss.ardupilot.org/t/failed-to-create-log-wont-log-this-session/30681
=> Clarify Log Creation Failure to GS, not board.

GCSViews/FlightPlanner.cs
Minor fix when setting home in flight planner with units other than meters.
=> Minor fix when setting home in flight planner

GCSViews/ConfigurationView/ConfigArducopter.de-DE.resx, GCSViews/ConfigurationView/ConfigArducopter.id-ID.resx, GCSViews/ConfigurationView/ConfigArducopter.it-IT.resx, GCSViews/ConfigurationView/ConfigArducopter.ja-JP.resx, GCSViews/ConfigurationView/ConfigArducopter.ko-KR.resx, GCSViews/ConfigurationView/ConfigArducopter.resx, GCSViews/ConfigurationView/ConfigArducopter.zh-Hant.resx, GCSViews/ConfigurationView/ConfigArducopter.zh-TW.resx, GCSViews/ConfigurationView/ConfigArdurover.resx
I can not find the extended tuning item CH 7, CH 8 in detail items.
I will discover RC 7, RC 8 in detail item.
I think that it is better to combine.
And CH6...
=> Change from option CH to option RC

ElevationProfile.cs
To show chart when UI is set up to use other units than meters.
=> Improved ElevationProfile to take units into account.

GCSViews/ConfigurationView/ConfigFailSafe.cs, GCSViews/ConfigurationView/ConfigFailSafe.resx
1. Allow to set Reserved MAH to 0 (Disabled)
2. Change for Japanese layout
=> Change the layout of BATT_MAH

ExtLibs/ArduPilot/CurrentState.cs
sonarrange is only downward.
I added these because I want to see the sensor's value of other direction.
=> Add the distance of DISTANCE_SENSOR to CurrentState

mavcmd.xml
Sub and Copter has this already, just needs to be added to Rover. It was recently merged into ArduPilot
https://github.com/ArduPilot/ardupilot/pull/12038
=> Rover: add waypoint item DO_NAV_DELAY

ExtLibs/px4uploader/Uploader.cs
this will give us some scope to rev the bl revision in the
future. Right now I can't rev it or all existing MP users would not be
able to upload
=> raise max bl revsion

ExtLibs/Comms/CommsUdpSerial.cs, MissionPlanner.csproj
Added a number of options to the drop down menus for coms rates in planner configuration
=> Coms rates update

README.md
Update how to compile instruction and formatting.
Those instruction were tested on fresh windows machine
=> Update readme informations

GCSViews/FlightPlanner.cs
We can change the mission altitude including decimals.
I think it's useful.
=> accept the float value in "Modify Alt" on Flight Planner screen

GCSViews/ConfigurationView/ConfigArducopter.Designer.cs
ACCEL ME and INPUT TC filed was missing change indication.
=> Advanced Tuning filed background color fix

GCSViews/FlightData.cs
Checks result of takeoff command in resume mission.
=> FlightData: Checks takeoff result in resume

ExtLibs/Utilities/Privacy.cs
The field which it should look for is Lat and not lat.
=> Log Anonimizer: Fix typo to make anonymizer work

ExtLibs/Controls/ControlHelpers.cs
config keys with dash are not saved, so changed the dash to underscore.
=> Fix HUD/EKF/VIBE position save/restore

GCSViews/FlightPlanner.cs
Adding a rotation input parameter to Text drawing tool in FlightPlanner.
=> FlightPlanner.cs: Add rotation parameter to AutoWP/Text

Properties/Resources.resx
Small description fix in Help view.
=> Help: fix shortcut description

ExtLibs/ArduPilot/CurrentState.cs
I added gps yaw to CurrentState.cs.
=> Add yaw of GPS_RAW_INT to CurrentState

plugins/InitialParamsCalculator.cs
Updated Initial Params Calculator according to Xfaxta's latest excel.
=> Plugin InitialParamsCalc : Update to latest calculations

ExtLibs/BouncyCastle/src/crypto/signers/SM2Signer.cs, ExtLibs/BouncyCastle/src/crypto/tls/DtlsReliableHandshake.cs, ExtLibs/BouncyCastle/src/crypto/tls/TlsUtilities.cs, ExtLibs/BouncyCastle/src/pkix/PkixCertPathValidatorUtilities.cs, ExtLibs/Controls/CustomMessageBox.cs, ExtLibs/MissionPlanner.Drawing/Pen.cs, ExtLibs/MissionPlanner.Drawing/SolidBrush.cs, ExtLibs/Ntrip/Program.cs, ExtLibs/Transitions/Transition.cs, ExtLibs/Transitions/Utility.cs, ExtLibs/UsbSerialForAndroid/Additions/SerialInputOutputManager.cs, ExtLibs/Utilities/LogMap.cs, GCSViews/ConfigurationView/ConfigHWCompass.cs, GCSViews/ConfigurationView/ConfigOSD.cs, GCSViews/ConfigurationView/ConfigREPL.cs, GCSViews/ConfigurationView/ConfigUAVCAN.cs, GCSViews/FlightPlanner.cs, MainV2.cs
I saw a lot of warnings appearing.
I believe that reducing the number of warnings is the best way to know what the real warnings are.
I made an unused response in the catch variable.
=> Repond to catch warning cs0168

ExtLibs/ArduPilot/CurrentState.cs, GCSViews/FlightData.cs
The modifications are as follows:
1. ExtLibs/ArduPilot/CurrentState.cs: add more MAVLink2 BATTERY STATUS information display
2. GCSViews/FlightData.cs: fix the incomplete display of string information
3. ExtLibs/ArduPilot/CurrentState.cs: Optimize string sorting
4. GCSViews/FlightData.cs: Optimize string sorting
=> Add and optimize display

ExtLibs/Utilities/DFLogBuffer.cs, Log/LogDownloadMavLink.cs
ConfigBattery: add QiotekZealotF427
Hardware introduce:
https://ardupilot.org/copter/docs/common-qiotek-zealot.html
=> ConfigBattery: add QiotekZealotF427

GCSViews/ConfigurationView/ConfigRadioInput.Designer.cs, GCSViews/ConfigurationView/ConfigRadioInput.cs, GCSViews/ConfigurationView/ConfigRadioInput.resx
I would add 15 and 16 calibrations to the RC inputs.
ArduPilot supports up to RCIN 15 and 16.
=> GCSViews: Add RC inputs 15 and 16

Common.cs
Suggested replacement of 2 string builder operations with interpolation.
=> Replaced 2 strings with interpolation

GCSViews/FlightPlanner.Designer.cs, GCSViews/FlightPlanner.cs, GCSViews/FlightPlanner.resx
Added a context menu option to draw a polygon using the currently displayed mission waypoints in the FlightPlanner view.  I will create a Discuss thread on the topic in addition to this PR.
=> Current waypoints to polygon feature

ExtLibs/ArduPilot/CurrentState.cs
Base on this https://github.com/ArduPilot/MissionPlanner/pull/2682.
Support two hygrometer sensors and delete the display of hygrometer id.
=> Hygrometer: support 2 hygrometer sensors

ExtLibs/Utilities/DisplayView.cs, GCSViews/ConfigurationView/ConfigInitialParams.Designer.cs, GCSViews/ConfigurationView/ConfigInitialParams.cs, GCSViews/ConfigurationView/ConfigInitialParams.resx, GCSViews/InitialSetup.cs, GCSViews/InitialSetup.resx, MissionPlanner.csproj
- Revamped InitialParameterCalculator to match with V1.6 version of the Excel
- Moved the calculator to the SETUP tab, right under FrameType.
=> Moving InitialParameterCalculator to the SETUP tab.

ExtLibs/Mavlink/Mavlink.cs, ExtLibs/Mavlink/message_definitions/ardupilotmega.xml, ExtLibs/Mavlink/message_definitions/common.xml, ExtLibs/Xamarin/Xamarin/Resources/mavcmd.xml, mavcmd.xml
=> Update mavlink xml and add SCRIPT_TIME mission item

Log/LogBrowse.cs
This adds a couple of things to the log review tool. 
-  the AP version string is added to the log window, like the main MP window when connected to a vehicle. 
- RCOut log displays the servo function name in a tool tip and in the graph label.
Only done RCOut so far, but would be easy to add labels for RCx_OPTIONS on rc input and IMU types for IMUs and compasses.
=> LogBrowse: display extra info from params with log items

GCSViews/ConfigurationView/ConfigAC_Fence.Designer.cs, GCSViews/ConfigurationView/ConfigAC_Fence.cs, GCSViews/ConfigurationView/ConfigAC_Fence.resx
I know that a minimum altitude has been added to the geofence.
I have added a minimum altitude item to the geofence.
AFTER
=> ConfigurationView: Add a minimum altitude item to the geofence setting screen

GCSViews/FlightData.Designer.cs
#2640 has been replaced.
I will be able to control servos 15 and 16, Relays 5 and 6 with the action buttons.
AFTER
=> GCSViews: Add Servo15,16 and Relay5,6

GCSViews/SITL.cs
=> Fix for canceling SITL version selection messagebox. ISSUE #2741

Common.cs
Fixed a typo on rover target/nav bearing, in ISSUE #2725
=> Fix a typo on rover target/nav bearing ISSUE #2725

Log/LogBrowse.cs
This adds some more log review tool tips, firstly it adds RC in to the existing field tips and graph legend, it copes with RC_MAP, Flight mode switch and RCx_OPTIONS. It displays combinations because it is possible, but not a good idea, to mix map and options.
Secondly it adds per instance tool tips:
Devid's for mag and baro:
Type for GPS:
As before there are a few more the instance ones we could add types to, `BAT`, `ARSP` ect. I will do another PR to add a few more in when I get a chance.
=> LogBrowse: add more tool tips from param

GCSViews/SITL.cs
Redo of previous PR. Fixing ISSUE #2733, selecting tradiheli SITL image.
=> Fix tradiheli stable/dev selection ISSUE #2733

ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/Czech/CzechGeographicMapProvider.cs, ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/Czech/CzechHistoryMapProvider.cs, ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/Czech/CzechHybridMapProvider.cs, ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/Czech/CzechMapProvider.cs, ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/Czech/CzechSatelliteMapProvider.cs, ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/Czech/CzechTuristWinterMapProvider.cs, ExtLibs/GMap.NET.Core/GMap.NET.MapProviders/GMapProvider.cs
Get the updated Czech map provider code from GMap.NET.
Note: Apparently there is no Hybrid Sat Map with the new API, it returns only sat map.
=> Update Czech map provider for the new api format.

mavcmd.xml
This is becoming an important mission item for fly/land/disarm/delay/arm/takeoff/fly/land missions
=> display DO_AUX_FUNCTION in mission editor

ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs
On a slow connection when readPacketAsync() is called repeatedly (for example during timeout/retries). It is possible to get packets out of sequence, which leads to incorrect packet loss indications.
The fix extends the Readlock block to include packet sequence checking. According to tests, this solves the issue.
Repro : Connect to an AP without GPS fix (no home position) via a real serial connection (USB to serial adapter to a telemetry port), or via a serial to ethernet converter (TCP or UDP) and upload a mission repeatedly. Check packet loss counter while uploading.
=> MavLinkInterface.readPacketAsync() include sequencing in Readlock

ExtLibs/ArduPilot/CurrentState.cs
these provide a really powerful method of manually tuning a VTOL
vehicle
=> added pidSRate and pidPDmod graph fields

GCSViews/ConfigurationView/ConfigFlightModes.cs
I found out that FLOWHOLD, ZIGZAG supports simple mode.
I have made it configurable in the flight mode screen.
=> GCSViews: FLOWHOLD and ZIGZAG support simple mode

ExtLibs/Utilities/Grid.cs, GCSViews/FlightPlanner.Designer.cs, GCSViews/FlightPlanner.cs, GCSViews/FlightPlanner.resx, Grid/GridData.cs, Grid/GridUI.Designer.cs, Grid/GridUI.cs, Grid/GridUI.resx
Added UI elements to expose number of laps in the grid circular pattern.
Added Offset Polygon to the Plan page
=> Grid: Circular Pattern Laps & GCSViews: Offset Polygon

mavcmd.xml
#2763 is supported.
AFTER
list
plan
file
=> PLAN: Add MAV_CMD_DO_SPRAYER to the command list

GCSViews/ConfigurationView/ConfigArducopter.Designer.cs
The filter values set on the extended tuning page are reversed for ROLL and PITCH.
=> fix filter param in the extended tuning page

ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs, GCSViews/FlightData.Designer.cs, GCSViews/FlightData.cs, GCSViews/FlightData.resx
This adds a button to send a message to the vehicle. 
This message is then send to the vehicle as a send text and show up in the log with `GCS:` prefix.
The longer term goal is to pull the string out when saving the log and append it to the file name. This gives a very easy method of keeping track of what it was you were doing in each flight.
=> Actions: add Send text button

GCSViews/ConfigurationView/ConfigInitialParams.cs, GCSViews/InitialSetup.cs
=> GCSViews: enable intial setup wizard for Quadplane

mavcmd.xml
I have added the following command to the list
DO_AUTOTUNE_ENABLE
DO_ENGINE_CONTROL
DO_SET_RESUME_REPEAT_DIST
AFTER
PLAN FILE:
=> Plan: Add to command list

GCSViews/ConfigurationView/ConfigRadioInput.cs, Joystick/JoystickAxis.cs, Joystick/JoystickSetup.cs
Change CH (channel) to RC (radio channel).
AFTER:
=> Joystick: Change from CH to RC

GCSViews/FlightData.cs, Plugins/OpenDroneID2/NMEA_GPS_Connection.cs, Plugins/OpenDroneID2/NMEA_Viewer.cs, Plugins/OpenDroneID2/OpenDroneID_Backend.cs, Plugins/OpenDroneID2/OpenDroneID_Plugin.cs, Plugins/OpenDroneID2/OpenDroneID_UI.Designer.cs, Plugins/OpenDroneID2/OpenDroneID_UI.cs, Plugins/OpenDroneID2/OpenDroneID_UI.resx
This supercedes PR 2930, which Mostly fixes for the NMEA threading and auto-connect. Also adds a version number to the UI. this fix changes the ODID messages out to be broadcast component, to avoid routing issues on the AP end.
=> ODID Plugin - Set outgoing messages to be broadcast

GCSViews/ConfigurationView/ConfigBatteryMonitoring.Designer.cs, GCSViews/ConfigurationView/ConfigBatteryMonitoring.cs, GCSViews/ConfigurationView/ConfigBatteryMonitoring.resx
Add Pixhawk 6C/Pix32 v6
Change Sensor: `Holybro Pixhawk 4 PM` to `Holybro Power Module`
=> ConfigBatteryMonitor: Add Pixhawk 6C/Pix32 v6

GCSViews/ConfigurationView/ConfigFailSafe.Designer.cs, GCSViews/ConfigurationView/ConfigFailSafe.cs, GCSViews/ConfigurationView/ConfigFailSafe.resx
I added a timeout entry to the battery fail-safe group.
It is not convenient to set the timeout from the parameter list.
AFTER
=> ConfigurationView: Add battery voltage low timeout

Controls/SerialOutputCoT.Designer.cs, Controls/SerialOutputCoT.cs, Controls/SerialOutputCoT.resx, ExtLibs/Utilities/CoT/contact.cs, ExtLibs/Utilities/CoT/detail.cs, ExtLibs/Utilities/CoT/uid_vmf.cs
added advanced button with vmf and callsign endpoint in the xml
=> CursorOnTarget: added advanced button with vmf and callsign endpoint

ExtLibs/Maps/Resources.resx, Properties/Resources.resx
This is where Tom Pittenger pats himself on the back
=> Thanks Tom!

GCSViews/SITL.Designer.cs, GCSViews/SITL.resx
=> added plane-3d sitl target

mavcmd.xml
updated the description of CONDITION_YAW parameters.
CONDITION_YAW's Angular Speed is already supported from Copter-4.1, by the following commit.
https://github.com/ArduPilot/ardupilot/commit/feae762e645e517e86a7fd9d61bca2cfc6b72070#diff-0e64ce1a1b5db8c13f7213375fb6ec4f06046136b39e1cbb312bc006284a9970R113
This PR
Previous
https://mavlink.io/en/messages/common.html#MAV_CMD_CONDITION_YAW
=> mavcmd: update CONDITION_YAW parameters

ExtLibs/ArduPilot/Mavlink/MAVLinkInterface.cs, GCSViews/FlightData.cs
Adds the ability to enable/disable High Latency mode via the Actions -> Do Action control
=> FlightData: Add action for MAV_CMD_CONTROL_HIGH_LATENCY

ExtLibs/Utilities/ParameterMetaDataParser.cs
fixes: "ERROR MissionPlanner.Utilities.ParameterMetaDataParser - Invalid MetaFrame Blimp"
=> Parameters: added Blimp

mavcmd.xml
=> support PAYLOAD_PLACE on planes

.github/workflows/mac.yml
The Xamarin version in macos-latest is not compatible with Xcode 14.2
=> GithubActions: force Xcode 14.0.1

temp.Designer.cs, temp.cs, temp.resx
See https://github.com/ArduPilot/MissionPlanner/issues/3059
Tested on a generic fmu 2.4.8
=> temp: ForceCalibration buttons

GCSViews/InitialSetup.resx
got a few complaints that this was confusing....this makes it specific to tuning setup, not general vehicle setup
=> Clarify setup helper name

mavcmd.xml
copter has it....even rover has it....plane should have it
=> add DO_GRIPPER to Plane

Utilities/Speech.cs
Fixes "cohver", "clanned", "cloiter", etc.
=> Speech: fix pronunciation of quadplane modes

Controls/SerialOutputCoT.Designer.cs, Controls/SerialOutputCoT.cs, Controls/SerialOutputCoT.resx, ExtLibs/Utilities/CoT/detail.cs, ExtLibs/Utilities/CoT/takv.cs
CoT/TAK: add detail takv and some cleanup
=> CoT/TAK: add detail takv and some cleanup

ExtLibs/ArduPilot/APFirmware.cs, ExtLibs/Controls/InputBox.cs
misc bug fixes/warnings that Visual Studio suggested plus one crash when fetching FW at start without internet
=> Misc bug fixes

ExtLibs/AltitudeAngelWings/Service/Settings.cs
To improve the authentication experience and security we have updated the redirect URL when logging into Altitude Angel services.
=> Update authentication redirect URL

ExtLibs/ArduPilot/CurrentState.cs, ExtLibs/Controls/HUD.cs, ExtLibs/Controls/HUDT.Designer.cs, ExtLibs/Controls/HUDT.resx, ExtLibs/Controls/HUDT.zh-Hans.resx, GCSViews/FlightData.Designer.cs, GCSViews/FlightData.cs
Addresses https://github.com/ArduPilot/MissionPlanner/issues/3124
Needed to add indication of safety state to HUD with this as well. I also did a little cleanup of unused inputs to a function, renamed a misspelling, and fixed a copy/paste error on the ARMED drawing size calculation.
=> FlightData: Actions: add safety switch toggle

ExtLibs/Utilities/MissionFile.cs
Added missing initializers to make JSON Mission export work
=> Fix json Mission export

GCSViews/ConfigurationView/ConfigArducopter.cs
Filter parameters and IMAX were missing
=> Fix missing params in QP Extended Tuning page

Controls/PropagationSettings.cs, Controls/PropagationSettings.resx, ExtLibs/Maps/Propagation.cs
I have added a filter by altitude to terrain display.
=> PropagationSettings: add altitude filter of terrain

ExtLibs/Xamarin/Xamarin/Resources/mavcmd.xml, mavcmd.xml
We have supported this for ages in AP but it never made it to the supported waypoint list. 
https://github.com/ArduPilot/ardupilot/pull/16746
=> maccmd.xml: add DO_SEND_SCRIPT_MESSAGE

ExtLibs/Mavlink/MAVLinkParam.cs, Log/LogBrowse.cs
1. Detect firmware type for loading correct metadata
2. Display default values if applicable
=> LogBrowse: improve parameter handling

ExtLibs/Maps/MapboxUser.cs
This was done in Mapbox already, but not MapboxUser
=> MapboxUser: increase MaxZoom to 24

GCSViews/ConfigurationView/ConfigPlanner.ko-KR.resx, GCSViews/ConfigurationView/ConfigPlanner.resx
Rearrange controls to show the language selection combobox
=> ConfigPlanner: Fix Korean localization

GCSViews/ConfigurationView/ConfigSerial.cs
Fix exception with less than five serial ports.
Fixes issue #3253
=> SerialConfig:Fix exception when with less than five serial ports

Controls/MovingBase.cs, Controls/SerialOutputCoT.cs, Controls/SerialOutputNMEA.cs, Controls/SerialOutputPass.cs, ExtLibs/Comms/CommsTCPSerial.cs, Plugins/OpenDroneID2/NMEA_GPS_Connection.cs, plugins/Dowding/DowdingUI.cs
Add ConfigRef in TCPSerial to save port and host to Settings with custom name
After port is closed, we do not autoReconnect
=> TCPSerial Fixes #3307

GCSViews/FlightData.Designer.cs, GCSViews/FlightData.resx
This expands the Relay count from 6 to 16. A better implementation would be to autodetect in the params RELAYn_FUNCTION > 0 to unhide it but this is a good first step and it matches the Servo out stuff that is above it
=> Add more relays

Controls/PreFlight/CheckListEditor.cs
The following updates have been made to the Preflight ChecklistEditor form:
1. The controls'  "+" button responds quicker
2. The controls' only display the "+" button next to each control item's last child item, and next to the main control item in the case when the control item does not have a child control item.
3. Bug fixes for when all items are removed from the form.
=> Preflight tab - Edit: CheckListEditor.cs updated add preflight sub checklist item functionality and response time

GCSViews/SITL.cs, Scripts/example9 - sitl.py
we no longer support --uartA format
=> SITL: fixed arguments for SITL launch

GCSViews/FlightData.Designer.cs, GCSViews/FlightData.cs, GCSViews/FlightData.ko-KR.resx, GCSViews/FlightData.resx, GCSViews/FlightData.zh-Hans.resx, GCSViews/FlightData.zh-Hant.resx, GCSViews/FlightData.zh-TW.resx, GCSViews/FlightPlanner.Designer.cs, GCSViews/FlightPlanner.cs, GCSViews/FlightPlanner.ko-KR.resx, GCSViews/FlightPlanner.resx, GCSViews/FlightPlanner.ru-RU.resx, GCSViews/FlightPlanner.zh-Hans.resx, GCSViews/FlightPlanner.zh-TW.resx
FlightData : Update Zoom level
FlightPlanner : Update Zoom level
Rename trackBar1 to TRK_zoom like in FlightData
TRK_zoom take min from map provider
TRK_zoom take now value from Map zoom in float instead of int
Add Zoom Numeric Up & Down to see Zoom level
=> Update Zoom level

ExtLibs/Utilities/DashWare.cs
User reported issue on Discord
I think this will solve it, but I'll need them to test first.
=> DashWare: fix culture bug

Controls/PropagationSettings.cs, Controls/PropagationSettings.resx, ExtLibs/Maps/GMapMarkerElevation.cs, ExtLibs/Maps/Propagation.cs
Add a switchable Scale to the elevation/terrain overlay.
=> Propagation: Add Scale to Elevation/Terrain Overlays

ExtLibs/Controls/HUD.cs
Fix battery cell voltage display while showing icons.
Fixes https://github.com/ArduPilot/MissionPlanner/issues/3402
=> HUD: Fix batterycell with icons

Controls/OpenGLtest2.cs
Tiles not rendered due an integer underflow.
Fix issue : 3D map not working #3441
=> 3D Map : Fix int underflow

ExtLibs/Utilities/GeoRefImageBase.cs
Roll, Pitch, Yaw field were changed to R, P, Y
=> GEORef: Fix changed field name in TRIG log message

GCSViews/FlightData.cs
Fixes #3462
Also adds two modes that were missing because we were looking for the old parameter name.
=> FlightData: update CMB_mountmode population

Joystick/Joy_Mount_Mode.cs
I should have caught this in #3464
=> Joy_Mount_Mode: fix metadata

Controls/SerialSupportProxy.Designer.cs, Controls/SerialSupportProxy.cs
=> SerialSupportProxy: add TCP option

GCSViews/ConfigurationView/ConfigSerialInjectGPS.zh-CN.resx, GCSViews/InitialSetup.cs, GCSViews/InitialSetup.zh-Hans.resx
Update title and most of labels.
=> Add translation of Simplified Chinese for RTCM/GPS Inject.

GCSViews/SITL.cs
Fix a stupid mistake from when I implemented #3459
=> SITL: fix dev download url

ExtLibs/ArduPilot/Mavlink/CameraProtocol.cs
Needs to handle -1 and 0 settings correctly
=> CameraProtocol: fix RequestMessageIntervals

GCSViews/FlightPlanner.cs
Fix custom and unknown command upload. (fall back to 1 multipliers)
=> Fix custom commands

.github/workflows/android.yml, .github/workflows/mac.yml, .github/workflows/main.yml
=> github: fixed CI builds

GCSViews/ConfigurationView/ConfigSerial.cs
fixing a long-lasting bug which scrambles the serial setup screen when the serial port numbers in the parameters are not consecutive.
=> ConfigSerial:Fix serial setup screen for non sequential serial ports

GCSViews/ConfigurationView/ConfigRawParams.cs
=> Add natural shorter to RawParam list and tree
